"""Shared fixtures for storage summary CLI unit tests."""

from __future__ import annotations

from repomap_kg.storage import (
    JSFrameworkSummaryRecord,
    NixSummaryRecord,
    PythonSummaryRecord,
    TerraformSummaryRecord,
)

def js_framework_summary_fixture() -> JSFrameworkSummaryRecord:
    return JSFrameworkSummaryRecord(
        root_path="/tmp/fixture",
        repository_name="fixture",
        framework_observations=42,
        framework_profiles={
            "node": 5,
            "express": 8,
            "nest": 6,
            "next": 7,
            "jest": 9,
            "jquery": 7,
            "generic_js": 4,
        },
        node={
            "entrypoints": 2,
            "requires": 4,
            "exports": 3,
            "env_references": 2,
        },
        express={
            "apps": 1,
            "routers": 1,
            "routes": 6,
            "middleware": 3,
            "error_handlers": 1,
            "dynamic_routes": 1,
        },
        nest={
            "modules": 1,
            "controllers": 2,
            "providers": 3,
            "routes": 5,
            "decorators": 12,
        },
        next={
            "pages": 3,
            "api_routes": 1,
            "app_routes": 2,
            "components": 2,
            "route_handlers": 1,
        },
        jest={
            "suites": 2,
            "tests": 4,
            "expectations": 6,
            "mocks": 2,
        },
        jquery={
            "selectors": 4,
            "events": 3,
            "ajax_references": 2,
            "plugin_references": 1,
        },
        generic_js={
            "canonical_routes": 6,
            "canonical_test_suites": 2,
            "canonical_test_cases": 4,
            "canonical_components": 2,
        },
        diagnostics={
            "framework_observation_limit": 1,
            "framework_selector_limit": 1,
        },
        safety={
            "no_execution": True,
            "no_fetch": True,
            "raw_profile_only": True,
            "no_new_canonical_namespaces": True,
        },
    )
def terraform_summary_fixture() -> TerraformSummaryRecord:
    return TerraformSummaryRecord(
        root_path="/tmp/fixture",
        repository_name="fixture",
        terraform_observations=120,
        terraform_files=8,
        file_families={
            "tf": 5,
            "tfvars": 1,
            "terraform.tfvars": 1,
            "auto.tfvars": 1,
        },
        terraform={
            "blocks": 35,
            "providers": 2,
            "required_providers": 2,
            "required_versions": 1,
            "backends": 1,
            "resources": 12,
            "data_sources": 2,
            "modules": 3,
            "variables": 10,
            "outputs": 4,
            "locals": 5,
            "moved": 1,
            "imports": 1,
            "checks": 1,
            "removed": 1,
        },
        references={
            "total": 20,
            "provider_sources": 2,
            "version_constraints": 3,
            "module_sources": 3,
            "local_module_refs": 1,
            "remote_refs_not_fetched": 2,
            "depends_on": 4,
            "provider_aliases": 1,
            "repo_escape_diagnostics": 1,
        },
        tfvars={
            "files": 3,
            "variables": 8,
            "literal_values_exposed": False,
        },
        redactions={
            "tfvars_values": 8,
            "secret_like_fields": 3,
            "credentialed_urls": 1,
            "import_ids": 1,
            "backend_values": 1,
        },
        diagnostics={
            "parse_errors": 1,
            "limit_overflows": 1,
            "malformed_hcl": 1,
        },
        generic_config={
            "config_documents": 0,
            "config_paths": 0,
            "config_references": 0,
            "file_nodes": 8,
        },
        safety={
            "no_execution": True,
            "no_fetch": True,
            "no_terraform_cli": True,
            "no_provider_download": True,
            "no_module_download": True,
            "no_state_access": True,
            "tfvars_redacted": True,
            "raw_profile_only": True,
            "no_new_canonical_namespaces": True,
        },
    )

def python_summary_fixture() -> PythonSummaryRecord:
    return PythonSummaryRecord(
        root_path="/tmp/fixture",
        repository_name="fixture",
        python_observations=250,
        package_files={"requirements": 3, "pyproject": 1},
        packaging={
            "requirements": 20,
            "dependency_groups": 4,
            "build_systems": 1,
            "entry_points": 3,
            "tool_configs": 8,
        },
        tests={
            "test_files": 12,
            "unittest_cases": 3,
            "pytest_tests": 20,
            "test_functions": 18,
            "test_methods": 5,
            "fixtures": 6,
            "parametrize": 2,
            "assertions": 80,
        },
        frameworks={
            "flask_apps": 1,
            "flask_blueprints": 2,
            "flask_routes": 8,
            "fastapi_apps": 1,
            "fastapi_routers": 2,
            "fastapi_routes": 10,
            "fastapi_dependencies": 5,
            "django_projects": 1,
            "django_apps": 2,
            "django_urlpatterns": 12,
            "django_views": 10,
            "django_models": 4,
            "django_setting_references": 8,
        },
        references={
            "total": 35,
            "package_refs": 15,
            "local_file_refs": 4,
            "direct_urls_not_fetched": 2,
            "index_urls_not_fetched": 2,
            "framework_refs": 12,
        },
        redactions={
            "credentialed_urls": 1,
            "private_indexes": 1,
            "secret_like_config": 2,
            "framework_settings": 1,
        },
        diagnostics={
            "parse_errors": 2,
            "limit_overflows": 1,
            "dynamic_constructs": 3,
        },
        generic_python={
            "modules": 20,
            "classes": 30,
            "functions": 80,
            "methods": 60,
            "imports": 40,
        },
        generic_config={
            "config_documents": 1,
            "config_paths": 60,
            "config_references": 5,
        },
        dogfooding={
            "repo_map_profile_observed": True,
            "bounded": True,
            "generated_report_committed": False,
        },
        safety={
            "no_execution": True,
            "no_imports": True,
            "no_test_execution": True,
            "no_framework_startup": True,
            "no_fetch": True,
            "no_package_install": True,
            "no_openapi_fetch": True,
            "raw_profile_only": True,
            "no_new_canonical_namespaces": True,
        },
    )

def nix_summary10_extra_count_maps():
    return {
        "flake_inputs": {
            "total": 4,
            "with_url": 3,
            "with_follows": 1,
            "redacted_sources": 4,
            "source_types": {
                "github": 1,
                "git": 0,
                "path": 1,
                "tarball": 0,
                "follows": 1,
                "unknown": 1,
                "dynamic": 0,
            },
        },
        "output_sections": {
            "total": 6,
            "by_section": {
                "packages": 1,
                "apps": 1,
                "devShells": 1,
                "checks": 1,
                "nixosModules": 1,
                "darwinModules": 0,
                "homeManagerModules": 0,
                "overlays": 1,
                "formatter": 0,
                "templates": 0,
                "legacyPackages": 0,
            },
            "by_family": {
                "output": 4,
                "module": 1,
                "overlay": 1,
                "formatter": 0,
                "template": 0,
                "legacy_package": 0,
            },
            "by_shape": {
                "direct_assignment": 4,
                "nested_attrset": 0,
                "inherit": 0,
                "merged_attrset": 0,
                "dynamic": 0,
                "helper_framework": 2,
                "unknown": 0,
            },
        },
        "dynamic_output_shapes": {
            "total": 2,
            "by_pattern": {
                "eachDefaultSystem": 1,
                "genAttrs": 1,
                "forAllSystems": 0,
                "flake-utils": 0,
                "flake-parts": 0,
                "string_interpolation": 0,
            },
        },
        "unsupported_flake_shapes": {
            "total": 3,
            "by_pattern": {
                "imported_outputs": 1,
                "merged_attrset": 1,
                "inherit_outputs": 0,
                "nested_attrset_without_direct_identity": 1,
                "template_section": 0,
                "legacy_packages_section": 0,
                "unknown_dynamic": 0,
            },
        },
    }

def nix_summary_fixture() -> NixSummaryRecord:
    return NixSummaryRecord(
        root_path="[root-path]",
        repository_name="fixture",
        nix_observations=21,
        nix_files=3,
        flake_files=1,
        raw={
            "imports": 1,
            "path_refs": 1,
            "apps": 1,
            "packages": 1,
            "dev_shells": 1,
            "checks": 1,
        },
        canonical={
            "apps": 1,
            "packages": 1,
            "dev_shells": 1,
            "checks": 1,
            "output_sections": 3,
        },
        edges={
            "import_sources": 1,
            "output_defines": 4,
            "output_section_defines": 3,
            "app_program_edges": 1,
        },
        programs={
            "app_programs_total": 1,
            "local": 1,
            "dynamic": 0,
            "external": 0,
            "unknown": 0,
        },
        paths={
            "path_refs_total": 1,
            "local": 1,
            "dynamic": 0,
            "unknown": 0,
            "repo_escaping_or_rejected": 0,
        },
        **nix_summary10_extra_count_maps(),
        generic_config={
            "config_documents": 17,
            "config_paths": 153,
            "config_references": 21,
            "config_parse_errors": 2,
            "config_redactions": 0,
        },
        diagnostics={
            "missing_output_identity": 0,
            "dynamic_imports": 0,
            "unknown_imports": 0,
            "unknown_app_programs": 0,
            "raw_only_path_refs": 1,
            "flake_files_without_output_observations": 0,
        },
        limitations={
            "flake_inputs_not_extracted": False,
            "overlays_not_extracted": True,
            "modules_not_classified": True,
            "packages_are_static_attr_counts_only": True,
            "no_nix_eval": True,
            "no_flake_lock_resolution": True,
            "path_values_omitted": True,
            "weak_output_sections_are_not_concrete_outputs": True,
        },
        safety={
            "read_only": True,
            "no_execution": True,
            "no_nix_cli": True,
            "no_fetch": True,
            "no_flake_lock_resolution": True,
            "no_store_inspection": True,
            "no_path_values": True,
            "private_paths_redacted": True,
            "raw_profile_only": True,
        },
    )
