"""Documented literal immutable targets for FIX2 resolver domain (REVISE39, ADR0066)."""

from __future__ import annotations

PYTHON_TARGETS: tuple[tuple[str, str], ...] = (
    ("actual_refresh_failure_causality", "FailureCausalityAuthority.record_code"),
    ("process_rss_monitor", "ProcessRssMonitor.run"),
    ("repomap_kg.cli.dispatch", "dispatch_command"),
    ("repomap_test_support.resource_test_images", "TestImageManager.build_ephemeral_image"),
    ("repomap_test_support.test_cov5k_r2_fix2_administrative", "execute_backup"),
    ("repomap_test_support.test_cov5k_r2_fix2_administrative", "execute_container_build"),
    ("repomap_test_support.test_cov5k_r2_fix2_administrative", "execute_container_removal"),
    ("repomap_test_support.test_cov5k_r2_fix2_administrative", "execute_container_start"),
    ("repomap_test_support.test_cov5k_r2_fix2_administrative", "execute_container_stop"),
    ("repomap_test_support.test_cov5k_r2_fix2_administrative", "execute_database_initialization"),
    ("repomap_test_support.test_cov5k_r2_fix2_administrative", "execute_database_removal"),
    ("repomap_test_support.test_cov5k_r2_fix2_administrative", "execute_docker_stats_diagnostic"),
    ("repomap_test_support.test_cov5k_r2_fix2_administrative", "execute_psql_native_load"),
    ("repomap_test_support.test_cov5k_r2_fix2_administrative", "execute_restore"),
    ("repomap_test_support.test_cov5k_r2_fix2_administrative", "execute_schema_migration"),
    ("repomap_test_support.test_cov5k_r2_fix2_administrative", "execute_test_harness"),
    ("repomap_test_support.test_cov5k_r2_fix2_gate_executor", "execute_complete_gate"),
    ("repomap_test_support.test_cov5k_r2_fix2_gate_executor", "execute_focused_selection"),
    ("repomap_test_support.test_cov5k_r2_fix2_gate_executor", "execute_former_failure_node"),
    ("repomap_test_support.test_cov5k_r2_fix2_observer", "execute_fresh_public_rehearsal"),
    ("repomap_test_support.test_cov5k_r2_fix2_observer", "execute_mixed_configured_campaign"),
    ("repomap_test_support.test_cov5k_r2_fix2_observer", "execute_observer_request"),
    ("repomap_test_support.test_cov5k_r2_fix2_observer", "execute_observer_schedule"),
    ("repomap_test_support.test_cov5k_r2_fix2_observer", "execute_owning_area_execution"),
    ("repomap_test_support.test_cov5k_r2_fix2_observer", "execute_prior_state_preservation"),
    ("repomap_test_support.test_cov5k_r2_fix2_preparation", "execute_preparation_condition"),
    ("repomap_test_support.test_cov5k_r2_fix2_preparation", "execute_preparation_state_path"),
    ("repomap_test_support.test_cov5k_r2_fix2_process_recorder", "ProcessBoundaryRecorder.run"),
    ("repomap_test_support.test_cov5k_r2_fix2_process_recorder", "execute_zero_process_boundary"),
    ("repomap_test_support.test_cov5k_r2_fix2_runtime", "execute_container_rss"),
    ("repomap_test_support.test_cov5k_r2_fix2_runtime", "execute_container_rss_equivalence"),
    ("repomap_test_support.test_cov5k_r2_fix2_runtime", "execute_failure_causality"),
    ("repomap_test_support.test_cov5k_r2_fix2_runtime", "execute_process_containment_companion"),
    ("repomap_test_support.test_cov5k_r2_fix2_runtime", "execute_process_rss"),
    ("repomap_test_support.test_cov5k_r2_fix2_runtime", "execute_runtime_driver_read"),
    ("repomap_test_support.test_cov5k_r2_fix2_runtime", "execute_terminal_live_cohort"),
    ("repomap_test_support.test_cov5k_r2_fix2_runtime", "execute_terminal_read"),
    ("repomap_test_support.test_cov5k_r2_fix2_runtime", "execute_terminal_stage_matrix"),
    ("run_tests", "main"),
    ("scale14_actual_refresh_supervisor", "ActualRefreshSupervisor"),
    ("scale15_actual_path_readback", "read_scale15_terminal_state"),
    ("scale15_actual_path_readback", "read_terminal_backend_summary"),
    ("scale28_backend_observer_session", "BackendObserverSession.run"),
    ("scale28_hybrid_startup", "prepare_parent_startup_authorities"),
    ("scale28_hybrid_startup", "prepare_startup_resources"),
    ("scale28_preparation_authority", "HybridPreparationAuthority.prepare"),
    ("scale28_preparation_worker", "PreparationWorkerAttempt"),
    ("scale28_runtime_identity", "capture_runtime_identity"),
)

EXTERNAL_TARGETS: tuple[str, ...] = (
    "tool:docker:rm",
    "tool:docker:start",
    "tool:docker:stats",
    "tool:docker:stop",
    "tool:psql",
)
