import pytest

from repomap_kg.service_package.contract import build_service_package_spec
from repomap_kg.service_package.systemd import (
    SystemdUserAdapter,
    decode_systemd_exec_argv,
)


def test_systemd_renders_one_private_user_unit_with_exact_argv(
    tmp_path, service_authority
):
    user_home = tmp_path / "user"
    repo_map_home = tmp_path / 'RepoMap % $ "quoted" Home'
    adapter = SystemdUserAdapter(user_home=user_home, uid=1000)
    spec = build_service_package_spec(repo_map_home)

    content = adapter.render(spec)
    text = content.decode("utf-8")

    assert adapter.target_path == (
        user_home / ".config" / "systemd" / "user" / "repomap-coordinator.service"
    )
    assert text.startswith("# Generated by RepoMap service package v1\n")
    assert "X-RepoMap-Service-Identity=org.repomap.coordinator" in text
    assert "X-RepoMap-Service-Package=1" in text
    assert f"X-RepoMap-Python-SHA256={spec.python_sha256}" in text
    assert f"X-RepoMap-Psql-SHA256={spec.psql_sha256}" in text
    assert "Type=simple" in text
    assert "Restart=on-failure" in text
    assert "RestartSec=10s" in text
    assert "StartLimitIntervalSec=" not in text
    assert "StartLimitBurst=" not in text
    assert "KillSignal=SIGTERM" in text
    assert "TimeoutStopSec=30s" in text
    assert "UMask=0077" in text
    assert "StandardOutput=\"append:" in text
    assert "StandardError=\"append:" in text
    assert "WantedBy=default.target" in text
    assert "Environment=" not in text
    assert "/bin/sh" not in text
    assert "synthetic-secret" not in text
    assert "%%" in text
    assert "$$" in text
    working_directory = next(
        line for line in text.splitlines() if line.startswith("WorkingDirectory=")
    )
    standard_output = next(
        line for line in text.splitlines() if line.startswith("StandardOutput=")
    )
    assert "%%" in working_directory
    assert "$$" not in working_directory
    assert "%%" in standard_output
    assert "$$" not in standard_output
    assert decode_systemd_exec_argv(content) == spec.foreground_argv
    adapter.validate(content, spec)
    assert adapter.recognizes(content)


def test_systemd_uses_exact_user_manager_commands(tmp_path):
    adapter = SystemdUserAdapter(user_home=tmp_path, uid=1000)
    unit = "repomap-coordinator.service"

    assert adapter.manager_probe_argv() == (
        "/usr/bin/systemctl",
        "--user",
        "show-environment",
    )
    assert adapter.inactive_return_codes() == frozenset({3})
    assert adapter.disabled_return_codes() == frozenset({1})
    assert adapter.active_probe_argv() == (
        "/usr/bin/systemctl",
        "--user",
        "is-active",
        "--quiet",
        unit,
    )
    assert adapter.enabled_probe_argv() == (
        "/usr/bin/systemctl",
        "--user",
        "is-enabled",
        "--quiet",
        unit,
    )
    assert adapter.reload_commands() == (
        ("/usr/bin/systemctl", "--user", "daemon-reload"),
    )
    assert adapter.enable_commands() == (
        ("/usr/bin/systemctl", "--user", "enable", unit),
    )
    assert adapter.start_commands() == (
        ("/usr/bin/systemctl", "--user", "start", unit),
    )
    assert adapter.stop_commands() == (
        ("/usr/bin/systemctl", "--user", "stop", unit),
    )
    assert adapter.disable_commands() == (
        ("/usr/bin/systemctl", "--user", "disable", unit),
    )
    assert adapter.restart_commands() == (
        ("/usr/bin/systemctl", "--user", "restart", unit),
    )


def test_systemd_rejects_nul_in_recognized_foreground_argv(tmp_path, service_authority):
    adapter = SystemdUserAdapter(user_home=tmp_path, uid=1000)
    spec = build_service_package_spec(tmp_path / "home")
    content = adapter.render(spec).replace(
        str(spec.repo_map_home).encode("utf-8"),
        b"/placeholder/\x00home",
        1,
    )

    assert not adapter.recognizes(content)


def test_systemd_rejects_modified_unit_authority(tmp_path, service_authority):
    adapter = SystemdUserAdapter(user_home=tmp_path, uid=1000)
    spec = build_service_package_spec(tmp_path / "home")
    content = adapter.render(spec).replace(
        b"[Install]\n",
        b"ExecStop=\"/bin/false\"\n\n[Install]\n",
    )

    assert not adapter.recognizes(content)


def test_systemd_rejects_an_arbitrary_non_python_executable(
    tmp_path, service_authority
):
    adapter = SystemdUserAdapter(user_home=tmp_path, uid=1000)
    spec = build_service_package_spec(tmp_path / "home")
    content = adapter.render(spec).replace(
        spec.foreground_argv[0].encode("utf-8"),
        b"/bin/echo",
        1,
    )

    assert not adapter.recognizes(content)


@pytest.mark.parametrize(
    "content",
    [
        b"not a unit",
        b"# Generated by RepoMap service package v1\n[Service]\nExecStart=/bin/true\n",
        (
            b"# Generated by RepoMap service package v1\n"
            b"[Unit]\nX-RepoMap-Service-Identity=org.repomap.coordinator\n"
            b"[Service]\nExecStart=\"/bin/sh\" \"-c\" \"repomap-kg\"\n"
        ),
    ],
)
def test_systemd_rejects_unrecognized_or_shell_definitions(
    tmp_path, service_authority, content
):
    adapter = SystemdUserAdapter(user_home=tmp_path, uid=1000)
    spec = build_service_package_spec(tmp_path / "home")

    assert not adapter.recognizes(content)
    with pytest.raises(ValueError, match="service_definition_invalid"):
        adapter.validate(content, spec)
