"""PowerShell command vocabulary used by static extraction."""

from __future__ import annotations


CANONICAL_CMDLETS = {
    name.lower(): name
    for name in (
        "Copy-Item",
        "Add-Content",
        "ConvertTo-SecureString",
        "Enter-PSSession",
        "Export-ModuleMember",
        "ForEach-Object",
        "Get-ChildItem",
        "Get-Content",
        "Get-Credential",
        "Get-ItemProperty",
        "Import-Module",
        "Install-Module",
        "Install-Package",
        "Invoke-Command",
        "Invoke-RestMethod",
        "Invoke-WebRequest",
        "Move-Item",
        "New-Item",
        "New-ItemProperty",
        "New-Object",
        "New-PSSession",
        "New-Service",
        "Remove-Item",
        "Remove-ItemProperty",
        "Register-ScheduledTask",
        "Set-Content",
        "Set-ExecutionPolicy",
        "Set-Item",
        "Set-ItemProperty",
        "Set-AuthenticodeSignature",
        "Set-Service",
        "Start-BitsTransfer",
        "Start-Process",
        "Start-Service",
        "Stop-Process",
        "Stop-Service",
        "Test-Path",
        "Uninstall-Module",
        "Uninstall-Package",
        "Unregister-ScheduledTask",
        "Update-Module",
        "Where-Object",
        "Write-Output",
    )
}
POWERSHELL_ALIASES = {
    "%": "ForEach-Object",
    "?": "Where-Object",
    "cat": "Get-Content",
    "cp": "Copy-Item",
    "curl": "Invoke-WebRequest",
    "del": "Remove-Item",
    "dir": "Get-ChildItem",
    "echo": "Write-Output",
    "gc": "Get-Content",
    "gci": "Get-ChildItem",
    "irm": "Invoke-RestMethod",
    "iwr": "Invoke-WebRequest",
    "ls": "Get-ChildItem",
    "mkdir": "New-Item",
    "mv": "Move-Item",
    "ni": "New-Item",
    "rm": "Remove-Item",
    "rmdir": "Remove-Item",
    "type": "Get-Content",
    "wget": "Invoke-WebRequest",
}
EXTERNAL_COMMANDS = frozenset(
    {
        "choco",
        "docker",
        "git",
        "kubectl",
        "npm",
        "pwsh",
        "python",
        "scoop",
        "terraform",
        "winget",
    }
)
COMMAND_SKIP_KEYWORDS = frozenset(
    {
        "break",
        "catch",
        "class",
        "continue",
        "data",
        "do",
        "else",
        "elseif",
        "finally",
        "for",
        "foreach",
        "from",
        "function",
        "if",
        "in",
        "param",
        "return",
        "switch",
        "throw",
        "trap",
        "try",
        "until",
        "using",
        "while",
        "workflow",
    }
)
