package extraction

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/lair001/repo-map-go-helper/internal/protocol"
)

func TestParseFileExtractsGO3DeclarationsInSourceOrder(t *testing.T) {
	path := writeSource(t, "declarations.go", `package sample
import (
    alias "example.invalid/alias"
    _ "example.invalid/blank"
    . "example.invalid/dot"
)
const (
    Exported = 1
    private = 2
)
var First, Second int
type Alias = string
type Generic[T any] struct { Value T }
func deferredUntilGO4() {}
`)

	result := ParseFile(path, "pkg/declarations.go")
	declarations := withoutGO6Observations(result.Observations)

	if len(result.Diagnostics) != 0 {
		t.Fatalf("ParseFile() diagnostics = %#v", result.Diagnostics)
	}
	wantKinds := []string{
		"go.package",
		"go.import", "go.import", "go.import",
		"go.const", "go.const",
		"go.var", "go.var",
		"go.type_alias", "go.type", "go.type_parameter", "go.constraint",
		"go.struct", "go.field", "go.function",
	}
	wantNames := []string{
		"sample",
		"example.invalid/alias", "example.invalid/blank", "example.invalid/dot",
		"Exported", "private",
		"First", "Second",
		"Alias", "Generic", "T", "", "Generic", "Value", "deferredUntilGO4",
	}
	if got := observationKinds(Result{Observations: declarations}); !reflect.DeepEqual(got, wantKinds) {
		t.Fatalf("kinds = %#v, want %#v", got, wantKinds)
	}
	if got := observationNames(Result{Observations: declarations}); !reflect.DeepEqual(got, wantNames) {
		t.Fatalf("names = %#v, want %#v", got, wantNames)
	}
	for _, observation := range result.Observations {
		if observation.Path != "pkg/declarations.go" {
			t.Fatalf("path = %q", observation.Path)
		}
		if observation.StartLine < 1 || observation.EndLine < observation.StartLine {
			t.Fatalf("invalid line range: %#v", observation)
		}
		if observation.Metadata["package_name"] != "sample" {
			t.Fatalf("package_name = %#v", observation.Metadata["package_name"])
		}
		if observation.Metadata["static_only"] != true || observation.Metadata["code_executed"] != false || observation.Metadata["type_checked"] != false {
			t.Fatalf("unsafe metadata = %#v", observation.Metadata)
		}
	}

	imports := declarations[1:4]
	if imports[0].Metadata["alias"] != "alias" || imports[1].Metadata["blank_import"] != true || imports[2].Metadata["dot_import"] != true {
		t.Fatalf("import metadata = %#v %#v %#v", imports[0].Metadata, imports[1].Metadata, imports[2].Metadata)
	}
	if imports[0].Target != "go.package-ref:example.invalid%2Falias" {
		t.Fatalf("import target = %q", imports[0].Target)
	}
	alias := declarations[8]
	generic := declarations[9]
	if alias.Metadata["exported"] != true || alias.Metadata["generic"] != false {
		t.Fatalf("alias metadata = %#v", alias.Metadata)
	}
	if generic.Metadata["generic"] != true || generic.Metadata["type_parameter_count"] != 1 {
		t.Fatalf("generic metadata = %#v", generic.Metadata)
	}
}

func TestParseFileMarksGeneratedTestVendorAndExternalTestContext(t *testing.T) {
	path := writeSource(t, "external_test.go", `// Code generated by test. DO NOT EDIT.
package sample_test
const Value = true
`)

	result := ParseFile(path, "vendor/example.invalid/sample/external_test.go")

	declarations := make([]protocol.Observation, 0, 2)
	for _, observation := range result.Observations {
		if observation.Kind == "go.package" || observation.Kind == "go.const" {
			declarations = append(declarations, observation)
		}
	}
	if len(declarations) != 2 {
		t.Fatalf("observations = %d", len(declarations))
	}
	for _, observation := range declarations {
		metadata := observation.Metadata
		if metadata["test_file"] != true || metadata["generated"] != true || metadata["vendor"] != true || metadata["partial_parse"] != false {
			t.Fatalf("context metadata = %#v", metadata)
		}
	}
	packageObservation := observationsByKind(result)["go.package"][0]
	if packageObservation.Metadata["external_test_package"] != true {
		t.Fatalf("package metadata = %#v", packageObservation.Metadata)
	}
}

func TestParseFileReturnsSafePartialFactsAndBoundedDiagnostics(t *testing.T) {
	source := "package broken\nimport \"example.invalid/safe\"\nconst BeforeError = 1\ntype Partial struct {\n" + strings.Repeat("@\n", 80)
	path := writeSource(t, "partial.go", source)

	result := ParseFile(path, "broken/partial.go")

	if len(result.Observations) == 0 {
		t.Fatal("ParseFile() emitted no partial observations")
	}
	if len(result.Diagnostics) == 0 || len(result.Diagnostics) > MaxDiagnostics {
		t.Fatalf("diagnostics = %d", len(result.Diagnostics))
	}
	if !result.Truncated {
		t.Fatal("Truncated = false, want true")
	}
	lastDiagnostic := result.Diagnostics[len(result.Diagnostics)-1]
	if lastDiagnostic.Code != "go-parse-errors-truncated" {
		t.Fatalf("last diagnostic = %#v", lastDiagnostic)
	}
	for _, observation := range result.Observations {
		if observation.Metadata["partial_parse"] != true {
			t.Fatalf("partial_parse = %#v", observation.Metadata["partial_parse"])
		}
		if observation.StartLine < 1 || observation.EndLine < observation.StartLine {
			t.Fatalf("invalid partial span = %#v", observation)
		}
		startOffset := observation.Metadata["start_offset"].(int)
		endOffset := observation.Metadata["end_offset"].(int)
		if startOffset < 0 || endOffset < startOffset {
			t.Fatalf("invalid partial offsets = %#v", observation.Metadata)
		}
	}
	for _, diagnostic := range result.Diagnostics {
		if strings.Contains(diagnostic.Message, path) || strings.Contains(diagnostic.Message, "@") {
			t.Fatalf("diagnostic leaked path or source: %#v", diagnostic)
		}
	}

	again := ParseFile(path, "broken/partial.go")
	if !reflect.DeepEqual(result, again) {
		t.Fatal("ParseFile() output is not deterministic")
	}
}

func TestParseFileOmitsPartialDeclarationsWithoutCompleteSpans(t *testing.T) {
	path := writeSource(t, "partial-eof.go", "package broken\ntype Partial struct {\n")

	result := ParseFile(path, "broken/partial-eof.go")

	for _, observation := range result.Observations {
		if observation.StartLine < 1 || observation.EndLine < observation.StartLine {
			t.Fatalf("invalid partial span = %#v", observation)
		}
		startOffset := observation.Metadata["start_offset"].(int)
		endOffset := observation.Metadata["end_offset"].(int)
		if startOffset < 0 || endOffset < startOffset {
			t.Fatalf("invalid partial offsets = %#v", observation.Metadata)
		}
	}
}

func writeSource(t *testing.T, name string, source string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(path, []byte(source), 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

func observationKinds(result Result) []string {
	kinds := make([]string, 0, len(result.Observations))
	for _, observation := range result.Observations {
		kinds = append(kinds, observation.Kind)
	}
	return kinds
}

func observationNames(result Result) []string {
	names := make([]string, 0, len(result.Observations))
	for _, observation := range result.Observations {
		names = append(names, observation.Name)
	}
	return names
}

func withoutGO6Observations(
	observations []protocol.Observation,
) []protocol.Observation {
	go6Kinds := map[string]struct{}{
		"go.reference": {}, "go.selector": {}, "go.call": {},
		"go.method_expression": {}, "go.construct": {}, "go.conversion": {},
		"go.type_assertion": {}, "go.type_switch": {}, "go.index": {},
		"go.slice": {}, "go.map_access": {}, "go.instantiation": {},
	}
	filtered := make([]protocol.Observation, 0, len(observations))
	for _, observation := range observations {
		if _, ok := go6Kinds[observation.Kind]; !ok {
			filtered = append(filtered, observation)
		}
	}
	return filtered
}
