package extraction

import (
	"encoding/json"
	"strings"
	"testing"
)

const buildContextSource = `// Code generated by fixture. DO NOT EDIT.
//go:build linux
// +build linux

package sample

// #cgo CFLAGS: -DPRIVATE_FIXTURE
import "C"
`

const testContextSource = `package sample_test
import "testing"
func TestFeature(t *testing.T) {}
func BenchmarkFeature(b *testing.B) {}
func FuzzFeature(f *testing.F) {}
func ExampleFeature() {}
func TestMain(m *testing.M) {}
func Testwrong(t *testing.T) {}
func TestWrongShape() {}
`

func TestParseFileExtractsBuildGeneratedCgoAndVendorContext(t *testing.T) {
	path := writeSource(t, "context.go", buildContextSource)

	result := ParseFile(path, "vendor/example.invalid/sample/context.go")
	byKind := observationsByKind(result)
	for _, kind := range []string{
		"go.build_constraint", "go.generated_marker", "go.cgo",
		"go.vendor_package",
	} {
		if len(byKind[kind]) == 0 {
			t.Fatalf("missing %s in %#v", kind, observationKinds(result))
		}
	}
	if len(byKind["go.build_constraint"]) != 2 {
		t.Fatalf("build constraints = %#v", byKind["go.build_constraint"])
	}
	if byKind["go.cgo"][0].Metadata["directive_count"] != 1 {
		t.Fatalf("cgo metadata = %#v", byKind["go.cgo"][0].Metadata)
	}
	payload, err := json.Marshal(result.Observations)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(payload), "PRIVATE_FIXTURE") {
		t.Fatal("context observation leaked a cgo directive")
	}
}

func TestParseFileExtractsSyntacticTestProfiles(t *testing.T) {
	path := writeSource(t, "context_test.go", testContextSource)

	result := ParseFile(path, "sample/context_test.go")
	byKind := observationsByKind(result)
	want := map[string]string{
		"go.test": "TestFeature", "go.benchmark": "BenchmarkFeature",
		"go.fuzz": "FuzzFeature", "go.example": "ExampleFeature",
		"go.test_main": "TestMain",
	}
	for kind, name := range want {
		if len(byKind[kind]) != 1 || byKind[kind][0].Name != name {
			t.Fatalf("%s = %#v", kind, byKind[kind])
		}
		if byKind[kind][0].Metadata["resolution"] != "syntactic" {
			t.Fatalf("%s metadata = %#v", kind, byKind[kind][0].Metadata)
		}
	}
	if len(byKind["go.test"]) != 1 {
		t.Fatalf("invalid test profiles were accepted: %#v", byKind["go.test"])
	}
	nonTestResult := ParseFile(path, "sample/context.go")
	if len(observationsByKind(nonTestResult)["go.test"]) != 0 {
		t.Fatal("test profile emitted outside a _test.go file")
	}
}
