import tempfile
import unittest
from pathlib import Path

from repomap_kg.extractors.languages.go_metadata import (
    detect_go_filename_constraints,
    detect_go_generated_marker,
    extract_go_metadata_observations,
)
from repomap_kg.graph.discovery import discover_observations, discover_repository
from repomap_kg.observations.raw import RawObservation


FIXTURE_ROOT = Path(__file__).parents[4] / "fixtures" / "go"


class GoDiscoveryUnitTests(unittest.TestCase):
    def test_invalid_utf8_go_file_remains_bounded(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            repository_root = Path(tmpdir)
            (repository_root / "invalid.go").write_bytes(b"\xff")

            file_info = discover_repository(repository_root)[0]
            observations = discover_observations(repository_root)

        self.assertEqual((file_info.language, file_info.role), ("go", "source"))
        self.assertEqual(observations[0].kind, "file")
        diagnostics = observations[1:]
        self.assertGreaterEqual(len(diagnostics), 1)
        self.assertLessEqual(len(diagnostics), 32)
        self.assertTrue(all(item.kind == "go.parse_error" for item in diagnostics))
        self.assertTrue(
            all(item.metadata["code_executed"] is False for item in diagnostics)
        )

    def test_filename_and_generated_marker_detection_is_conservative(self):
        self.assertEqual(
            detect_go_filename_constraints("pkg/worker_linux.go"),
            ("linux", None, False),
        )
        self.assertEqual(
            detect_go_filename_constraints("pkg/worker_arm64_test.go"),
            (None, "arm64", True),
        )
        self.assertEqual(
            detect_go_filename_constraints("pkg/worker.go"),
            (None, None, False),
        )
        self.assertEqual(
            detect_go_generated_marker(
                "// Code generated by fixture. DO NOT EDIT.\npackage pkg\n"
            ),
            1,
        )
        self.assertIsNone(
            detect_go_generated_marker(
                "package pkg\n// Code generated too late. DO NOT EDIT.\n"
            )
        )
        self.assertIsNone(detect_go_generated_marker(""))

    def test_classifies_go_source_test_generated_and_metadata_files(self):
        file_infos = discover_repository(FIXTURE_ROOT)
        by_path = {file_info.path: file_info for file_info in file_infos}

        regular = by_path["classification/regular.go"]
        self.assertEqual(
            (regular.language, regular.role, regular.generated),
            ("go", "source", False),
        )

        test_file = by_path["classification/widget_test.go"]
        self.assertEqual(
            (test_file.language, test_file.role, test_file.generated),
            ("go", "test", False),
        )

        generated = by_path["classification/zz_generated_test.go"]
        self.assertEqual(
            (generated.language, generated.role, generated.generated),
            ("go", "generated", True),
        )

        self.assertEqual(by_path["module_basic/go.mod"].language, "go-module")
        self.assertEqual(by_path["module_basic/go.mod"].role, "config")
        self.assertEqual(by_path["module_basic/go.sum"].language, "go-checksum")
        self.assertEqual(by_path["workspace_basic/go.work"].language, "go-workspace")
        vendor_manifest = by_path["workspace_basic/vendor/modules.txt"]
        self.assertEqual(
            (vendor_manifest.language, vendor_manifest.role),
            ("go-vendor-manifest", "config"),
        )

    def test_emits_go_file_module_and_workspace_observations(self):
        observations = discover_observations(FIXTURE_ROOT)
        by_kind: dict[str, list[RawObservation]] = {}
        for observation in observations:
            by_kind.setdefault(observation.kind, []).append(observation)

        self.assertEqual(len(by_kind["go.file"]), 17)
        assembly = by_kind["go.assembly_companion"]
        self.assertEqual(len(assembly), 1)
        self.assertEqual(assembly[0].path, "syntax_basic/context.s")
        self.assertEqual(assembly[0].metadata["package_name"], "sample")
        generated = next(
            item
            for item in by_kind["go.file"]
            if item.path.endswith("zz_generated_test.go")
        )
        self.assertEqual(
            {
                key: generated.metadata[key]
                for key in ("test_file", "generated", "vendor")
            },
            {"test_file": True, "generated": True, "vendor": False},
        )
        constrained = next(
            item
            for item in by_kind["go.file"]
            if item.path.endswith("worker_linux_amd64.go")
        )
        self.assertEqual(
            (constrained.metadata["goos"], constrained.metadata["goarch"]),
            ("linux", "amd64"),
        )

        module = next(
            item
            for item in by_kind["go.module"]
            if item.name == "example.invalid/module-basic"
        )
        self.assertEqual(module.name, "example.invalid/module-basic")
        module_versions = {
            item.name
            for item in by_kind["go.module_go_version"]
            if item.metadata.get("owner_module_path") == module.name
        }
        self.assertEqual(module_versions, {"1.25"})
        self.assertEqual(by_kind["go.module_toolchain"][0].name, "go1.25.3")
        module_requirements = [
            item
            for item in by_kind["go.module_require"]
            if item.metadata.get("owner_module_path") == module.name
        ]
        self.assertEqual(len(module_requirements), 3)
        indirect = next(
            item for item in module_requirements if item.metadata["indirect"]
        )
        self.assertEqual(indirect.name, "example.invalid/indirect")
        commented = next(
            item
            for item in module_requirements
            if item.name == "example.invalid/commented"
        )
        self.assertFalse(commented.metadata["indirect"])
        self.assertEqual(len(by_kind["go.module_replace"]), 2)
        self.assertEqual(len(by_kind["go.module_exclude"]), 1)
        self.assertEqual(len(by_kind["go.module_retract"]), 1)
        self.assertEqual(by_kind["go.metadata_unknown"][0].name, "future")

        workspace = by_kind["go.workspace"][0]
        self.assertEqual(workspace.path, "workspace_basic/go.work")
        self.assertEqual(by_kind["go.workspace_go_version"][0].name, "1.25")
        self.assertEqual(by_kind["go.workspace_toolchain"][0].name, "go1.25.3")
        self.assertEqual(
            [item.name for item in by_kind["go.workspace_use"]],
            ["workspace_basic/app", "workspace_basic/lib"],
        )
        self.assertEqual(len(by_kind["go.workspace_replace"]), 1)

    def test_malformed_metadata_is_bounded_and_later_directives_survive(self):
        observations = discover_observations(FIXTURE_ROOT / "malformed")
        kinds = {item.kind for item in observations}
        self.assertIn("go.metadata_parse_error", kinds)

        parse_errors = [
            item for item in observations if item.kind == "go.metadata_parse_error"
        ]
        self.assertEqual(len(parse_errors), 3)
        self.assertEqual(
            {item.metadata["error_kind"] for item in parse_errors},
            {"invalid-quoting", "unterminated-block"},
        )
        module = next(item for item in observations if item.kind == "go.module")
        self.assertEqual(module.name, "example.invalid/recovered")
        requirement = next(
            item for item in observations if item.kind == "go.module_require"
        )
        self.assertFalse(requirement.metadata["indirect"])

    def test_invalid_directives_and_external_paths_are_bounded(self):
        observations = extract_go_metadata_observations(
            "nested/go.mod",
            "\n".join(
                (
                    "module example.invalid/bounds",
                    "go 1.25 extra",
                    "replace example.invalid/old => /private/external",
                    "replace example.invalid/missing-target",
                    "replace old v1.0.0 extra => replacement",
                    "retract v1.2.3",
                    "retract",
                )
            ),
        )

        errors = [
            item for item in observations if item.kind == "go.metadata_parse_error"
        ]
        self.assertEqual(len(errors), 4)
        replacement = next(
            item for item in observations if item.kind == "go.module_replace"
        )
        self.assertEqual(replacement.target, "external-path:<redacted>")
        self.assertEqual(replacement.metadata["replacement"], "<repository-relative>")
        retract = next(
            item for item in observations if item.kind == "go.module_retract"
        )
        self.assertEqual(
            (retract.metadata["low"], retract.metadata["high"]),
            ("v1.2.3", "v1.2.3"),
        )
        self.assertFalse(retract.metadata["rationale_present"])
        self.assertEqual(extract_go_metadata_observations("go.sum", "ignored"), ())


if __name__ == "__main__":
    unittest.main()
