"""Canonical edge-kind vocabulary shared by public graph readback surfaces."""

from __future__ import annotations

__all__ = ("CANONICAL_EDGE_KINDS",)


CANONICAL_EDGE_KINDS = frozenset(
    (
        "asserts",
        "benchmarks",
        "calls",
        "command_intent",
        "command_under_test",
        "completion_for",
        "configures",
        "constructs",
        "contains",
        "declares",
        "defers",
        "defines",
        "depends_on",
        "embeds",
        "examples",
        "executes",
        "expects",
        "exposes_script",
        "fuzzes",
        "has_assertion",
        "has_hook",
        "has_test_case",
        "host_mutation_intent",
        "imports",
        "includes",
        "instance_of",
        "instantiates",
        "links_to",
        "loads",
        "method_of",
        "mutates_host",
        "network_intent",
        "package_intent",
        "panics",
        "pipe_command_intent",
        "reads",
        "reads_env",
        "receives",
        "recovers",
        "references",
        "refutes",
        "replaces_module",
        "requires_module",
        "returns",
        "selects",
        "sends",
        "sources",
        "starts_goroutine",
        "styles",
        "system_command_intent",
        "tests",
        "tests_command",
        "uses_builtin",
        "uses_fixture",
        "uses_helper",
        "uses_mock",
        "uses_package_manager",
        "uses_plugin",
        "uses_plugin_manager",
        "uses_stub",
        "uses_zsh_module",
        "workspace_uses",
        "wraps",
        "writes",
        "writes_env",
    )
)
