"""Compatibility facade for conservative office-document extraction."""

from __future__ import annotations

from repomap_kg.extractors.documents.office_references import (
    EXTRACTOR_NAME,
    MAX_TEXT_SUMMARY_CHARS,
    ODF_INTERNAL_REFERENCE_TARGET,
    ODF_NAMESPACES,
    ODF_SAFE_PARTS,
    PATH_PATTERN,
    SECRET_PRONE_MARKERS,
    URL_PATTERN,
    _contains_secret_marker,
    _latex_reference,
    _odf_href_values,
    _odf_manifest_references,
    _odf_reference,
    _q,
    _redacted_or_summary,
    _Reference,
    _reference_for_value,
    _reference_observations,
    _references_from_text,
    _safe_summary,
    _safe_value_summary,
    _target_key_for_reference,
)
from repomap_kg.extractors.documents.office_common import (
    PARSER_NAME,
    _column_type_summary,
    _parse_error,
    _pointer_for_slug,
    _scalar_type,
    _slugify,
)
from repomap_kg.extractors.documents.office_odf import (
    DEFAULT_MAX_FILE_COUNT,
    DEFAULT_MAX_PACKAGE_BYTES,
    DEFAULT_MAX_PART_BYTES,
    DEFAULT_MAX_UNCOMPRESSED_BYTES,
    MAX_COMPRESSION_RATIO,
    ODF_FORMATS,
    extract_odf_file_observations,
    _element_text,
    _extract_odf_spreadsheet,
    _extract_odf_text_document,
    _has_ancestor,
    _odf_formula_count,
    _odf_heading_level,
    _odf_meta_title,
    _odf_package_metadata,
    _odf_package_safety_error,
    _odf_repeat_count,
    _odf_style_count,
    _odf_table_name,
    _odf_table_observations,
    _odf_table_rows,
    _parent_map,
    _xml_bytes_are_dangerous,
)
from repomap_kg.extractors.documents.office_plain import (
    LATEX_COMMAND_PATTERN,
    LATEX_COMMANDS,
    LATEX_SECTION_LEVELS,
    MAX_ROWS,
    TXT_HEADING_PATTERN,
    extract_document_file_observations,
    _extract_latex,
    _extract_table,
    _extract_text,
    _looks_like_header,
    _strip_latex_comments,
)
from repomap_kg.graph.keys import (
    document_column_key,
    document_file_key,
    document_latex_command_key,
    document_section_key,
    document_sheet_key,
    document_table_key,
)
