"""Email storage summary SQL builder."""

from __future__ import annotations

from repomap_kg.storage.sql_core import sql_literal


def build_email_summary_query_sql(root_path: str) -> str:
    quoted_root = sql_literal(root_path)
    return (
        "WITH repo AS ("
        "SELECT id, name, root_path FROM repositories "
        f"WHERE repositories.root_path = {quoted_root}"
        "), "
        "email_nodes AS ("
        "SELECT canonical_nodes.* FROM canonical_nodes "
        "JOIN repo ON repo.id = canonical_nodes.repository_id "
        "WHERE canonical_nodes.graph_key_version = 1 "
        "AND canonical_nodes.kind LIKE 'email.%'"
        "), "
        "email_raw AS ("
        "SELECT raw_observations.* FROM raw_observations "
        "JOIN repo ON repo.id = raw_observations.repository_id "
        "WHERE raw_observations.kind LIKE 'email.%'"
        "), "
        "email_references AS ("
        "SELECT canonical_edges.* FROM canonical_edges "
        "JOIN repo ON repo.id = canonical_edges.repository_id "
        "WHERE canonical_edges.graph_key_version = 1 "
        "AND canonical_edges.edge_kind = 'references' "
        "AND canonical_edges.source_canonical_key LIKE 'email.%'"
        ") "
        "SELECT json_build_object("
        f"'root_path', {quoted_root}, "
        "'repository_name', (SELECT name FROM repo), "
        "'mailboxes', (SELECT COUNT(*) FILTER (WHERE kind = 'email.mailbox') "
        "FROM email_nodes), "
        "'messages', (SELECT COUNT(*) FILTER (WHERE kind = 'email.message') "
        "FROM email_nodes), "
        "'eml_messages', (SELECT COUNT(*) FROM email_nodes "
        "WHERE kind = 'email.message' "
        "AND metadata_json->>'format' = 'eml'), "
        "'mbox_messages', (SELECT COUNT(*) FROM email_nodes "
        "WHERE kind = 'email.message' "
        "AND metadata_json->>'format' = 'mbox'), "
        "'addresses', (SELECT COUNT(*) FILTER (WHERE kind = 'email.address') "
        "FROM email_nodes), "
        "'address_observations', (SELECT COUNT(*) FROM email_raw raw_observations "
        "WHERE raw_observations.kind = 'email.address'), "
        "'address_domains', (SELECT COUNT(DISTINCT metadata_json->>'address_domain') "
        "FROM email_nodes WHERE kind = 'email.address' "
        "AND metadata_json ? 'address_domain'), "
        "'mime_parts', (SELECT COUNT(*) FILTER (WHERE kind = 'email.part') "
        "FROM email_nodes), "
        "'text_plain_parts', (SELECT COUNT(*) FROM email_nodes "
        "WHERE kind = 'email.part' "
        "AND metadata_json->>'content_type' = 'text/plain'), "
        "'text_html_parts', (SELECT COUNT(*) FROM email_nodes "
        "WHERE kind = 'email.part' "
        "AND metadata_json->>'content_type' = 'text/html'), "
        "'attachment_stubs', (SELECT COUNT(*) FILTER "
        "(WHERE kind = 'email.attachment_stub') FROM email_nodes), "
        "'inline_attachments', (SELECT COUNT(*) FROM email_nodes "
        "WHERE kind = 'email.attachment_stub' "
        "AND COALESCE((metadata_json->>'inline')::boolean, false)), "
        "'content_id_parts', (SELECT COUNT(*) FROM email_nodes "
        "WHERE kind IN ('email.part', 'email.attachment_stub') "
        "AND COALESCE((metadata_json->>'content_id_present')::boolean, false)), "
        "'thread_hints', (SELECT COUNT(*) FILTER "
        "(WHERE kind = 'email.thread_hint') FROM email_nodes), "
        "'message_references', (SELECT COUNT(*) FROM email_references "
        "WHERE target_canonical_key LIKE 'email.message:%' "
        "OR target_canonical_key LIKE 'unknown:email-message:%'), "
        "'external_url_references', (SELECT COUNT(*) FROM email_references "
        "WHERE target_canonical_key LIKE 'external.url:%'), "
        "'list_unsubscribe_references', (SELECT COUNT(*) FROM email_raw raw_observations "
        "WHERE raw_observations.kind = 'email.reference' "
        "AND raw_observations.payload_json->'metadata'->>'reference_kind' = "
        "'list_unsubscribe'), "
        "'parse_errors', (SELECT COUNT(*) FROM email_raw raw_observations "
        "WHERE raw_observations.kind = 'email.parse_error'), "
        "'malformed_or_oversized_diagnostics', (SELECT COUNT(*) "
        "FROM email_raw raw_observations "
        "WHERE raw_observations.kind = 'email.parse_error' "
        "AND (raw_observations.payload_json->'metadata'->>'error_kind' "
        "LIKE '%limit%' "
        "OR raw_observations.payload_json->'metadata'->>'error_kind' "
        "LIKE '%malformed%' "
        "OR raw_observations.payload_json->'metadata'->>'error_kind' "
        "= 'mbox-missing-from-separator')), "
        "'message_id_present', (SELECT COUNT(*) FROM email_nodes "
        "WHERE kind = 'email.message' "
        "AND COALESCE((metadata_json->>'message_id_present')::boolean, false)), "
        "'message_id_missing_or_invalid', (SELECT COUNT(*) FROM email_nodes "
        "WHERE kind = 'email.message' "
        "AND NOT (COALESCE((metadata_json->>'message_id_present')::boolean, false) "
        "AND COALESCE((metadata_json->>'message_id_valid')::boolean, false))), "
        "'messages_with_attachments', (SELECT COUNT(*) FROM email_nodes "
        "WHERE kind = 'email.message' "
        "AND COALESCE((metadata_json->>'has_attachments')::boolean, false)), "
        "'messages_with_html', (SELECT COUNT(*) FROM email_nodes "
        "WHERE kind = 'email.message' "
        "AND COALESCE((metadata_json->>'has_text_html')::boolean, false)), "
        "'messages_with_plain', (SELECT COUNT(*) FROM email_nodes "
        "WHERE kind = 'email.message' "
        "AND COALESCE((metadata_json->>'has_text_plain')::boolean, false)), "
        "'mailbox_limits', (SELECT COUNT(*) FROM email_nodes "
        "WHERE kind = 'email.mailbox' "
        "AND COALESCE("
        "(metadata_json->>'mailbox_message_count_limited')::boolean, "
        "false)), "
        "'no_provider_api', true, "
        "'no_mutation', true, "
        "'no_body_text', true, "
        "'no_attachment_content', true"
        ")::text;"
    )
