"""SQL builders for RepoMap storage domain and manifest summary readback."""

from __future__ import annotations

from repomap_kg.storage.sql_core import sql_literal

__all__ = (
    "build_openapi_summary_query_sql",
    "build_terraform_summary_query_sql",
    "build_bulk_summary_query_sql",
    "build_api_summary_query_sql",
)


def build_openapi_summary_query_sql(root_path: str) -> str:
    quoted_root = sql_literal(root_path)
    return (
        "WITH repo AS ("
        "SELECT id, name, root_path FROM repositories "
        f"WHERE repositories.root_path = {quoted_root}"
        "), "
        "raw AS ("
        "SELECT raw_observations.* FROM raw_observations "
        "JOIN repo ON repo.id = raw_observations.repository_id"
        "), "
        "openapi_raw AS ("
        "SELECT * FROM raw WHERE kind LIKE 'openapi.%'"
        "), "
        "canonical_config AS ("
        "SELECT canonical_nodes.* FROM canonical_nodes "
        "JOIN repo ON repo.id = canonical_nodes.repository_id "
        "WHERE canonical_nodes.graph_key_version = 1 "
        "AND canonical_nodes.kind IN ('config.document', 'config.path')"
        ") "
        "SELECT json_build_object("
        f"'root_path', {quoted_root}, "
        "'repository_name', (SELECT name FROM repo), "
        "'openapi_observations', (SELECT COUNT(*) FROM openapi_raw), "
        "'openapi_documents', (SELECT COUNT(*) FROM openapi_raw "
        "WHERE kind = 'openapi.document'), "
        "'spec_families', json_build_object("
        "'openapi3', (SELECT COUNT(*) FROM openapi_raw "
        "WHERE kind = 'openapi.document' "
        "AND payload_json->'metadata'->>'spec_family' = 'openapi3'), "
        "'swagger2', (SELECT COUNT(*) FROM openapi_raw "
        "WHERE kind = 'openapi.document' "
        "AND payload_json->'metadata'->>'spec_family' = 'swagger2')), "
        "'openapi', json_build_object("
        "'info', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.info'), "
        "'servers', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.server'), "
        "'paths', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.path'), "
        "'operations', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.operation'), "
        "'parameters', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.parameter'), "
        "'request_bodies', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.request_body'), "
        "'responses', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.response'), "
        "'schemas', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.schema'), "
        "'components', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.component'), "
        "'security_schemes', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.security_scheme'), "
        "'tags', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.tag'), "
        "'examples', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.example')), "
        "'methods', json_build_object("
        "'GET', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.operation' "
        "AND UPPER(COALESCE(payload_json->'metadata'->>'method', '')) = 'GET'), "
        "'POST', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.operation' "
        "AND UPPER(COALESCE(payload_json->'metadata'->>'method', '')) = 'POST'), "
        "'PUT', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.operation' "
        "AND UPPER(COALESCE(payload_json->'metadata'->>'method', '')) = 'PUT'), "
        "'PATCH', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.operation' "
        "AND UPPER(COALESCE(payload_json->'metadata'->>'method', '')) = 'PATCH'), "
        "'DELETE', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.operation' "
        "AND UPPER(COALESCE(payload_json->'metadata'->>'method', '')) = 'DELETE'), "
        "'OPTIONS', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.operation' "
        "AND UPPER(COALESCE(payload_json->'metadata'->>'method', '')) = 'OPTIONS'), "
        "'HEAD', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.operation' "
        "AND UPPER(COALESCE(payload_json->'metadata'->>'method', '')) = 'HEAD'), "
        "'TRACE', (SELECT COUNT(*) FROM openapi_raw WHERE kind = 'openapi.operation' "
        "AND UPPER(COALESCE(payload_json->'metadata'->>'method', '')) = 'TRACE')), "
        "'references', json_build_object("
        "'internal_refs', (SELECT COUNT(*) FROM openapi_raw "
        "WHERE kind = 'openapi.reference' "
        "AND payload_json->'metadata'->>'reference_scope' = 'internal'), "
        "'local_file_refs', (SELECT COUNT(*) FROM openapi_raw "
        "WHERE kind = 'openapi.reference' "
        "AND payload_json->'metadata'->>'reference_scope' = 'local_file'), "
        "'remote_refs_not_fetched', (SELECT COUNT(*) FROM openapi_raw "
        "WHERE kind = 'openapi.reference' "
        "AND payload_json->'metadata'->>'reference_scope' = 'remote' "
        "AND COALESCE((payload_json->'metadata'->>'not_fetched')::boolean, false)), "
        "'external_docs_not_fetched', (SELECT COUNT(*) FROM openapi_raw "
        "WHERE kind = 'openapi.reference' "
        "AND payload_json->'metadata'->>'reference_scope' = 'external_docs' "
        "AND COALESCE((payload_json->'metadata'->>'not_fetched')::boolean, false)), "
        "'refs_not_fetched', (SELECT COUNT(*) FROM openapi_raw "
        "WHERE kind = 'openapi.reference' "
        "AND COALESCE((payload_json->'metadata'->>'not_fetched')::boolean, false))), "
        "'redactions', json_build_object("
        "'credentialed_urls', (SELECT COUNT(*) FROM openapi_raw "
        "WHERE payload_json->'metadata'->>'redaction_reason' = 'credentialed-url'), "
        "'openapi_ref_summaries', (SELECT COUNT(*) FROM openapi_raw "
        "WHERE kind = 'openapi.redaction' "
        "AND payload_json->'metadata'->>'redaction_reason' = 'openapi-ref-summary-only'), "
        "'text_summaries', (SELECT COUNT(*) FROM openapi_raw "
        "WHERE kind = 'openapi.redaction' "
        "AND payload_json->'metadata'->>'redaction_reason' = 'openapi-text-summary-only'), "
        "'example_summaries', (SELECT COUNT(*) FROM openapi_raw "
        "WHERE kind = 'openapi.redaction' "
        "AND payload_json->'metadata'->>'redaction_reason' = 'openapi-example-summary-only'), "
        "'secret_prone_fields', (SELECT COUNT(*) FROM openapi_raw "
        "WHERE kind = 'openapi.redaction' "
        "AND payload_json->'metadata'->>'redaction_reason' = 'secret-prone-openapi-field')), "
        "'diagnostics', json_build_object("
        "'parse_errors', (SELECT COUNT(*) FROM openapi_raw "
        "WHERE kind = 'openapi.parse_error'), "
        "'unsupported_specs', (SELECT COUNT(*) FROM openapi_raw "
        "WHERE kind = 'openapi.parse_error' "
        "AND payload_json->'metadata'->>'error_kind' IN ("
        "'unsupported-openapi-document', 'unsupported-openapi-version')), "
        "'limit_overflows', (SELECT COUNT(*) FROM openapi_raw "
        "WHERE kind = 'openapi.parse_error' "
        "AND payload_json->'metadata'->>'error_kind' IN ("
        "'openapi-path-limit', 'openapi-operation-limit', "
        "'openapi-schema-limit', 'openapi-parameter-limit', "
        "'openapi-response-limit', 'openapi-reference-limit')), "
        "'local_ref_errors', (SELECT COUNT(*) FROM openapi_raw "
        "WHERE kind = 'openapi.parse_error' "
        "AND payload_json->'metadata'->>'error_kind' = 'openapi-local-ref-outside-root'), "
        "'malformed_specs', (SELECT COUNT(*) FROM raw "
        "WHERE kind IN ('config.parse_error', 'openapi.parse_error') "
        "AND payload_json->'metadata'->>'error_kind' IN ("
        "'malformed-openapi-json', 'malformed-openapi-yaml'))), "
        "'generic_config', json_build_object("
        "'config_documents', (SELECT COUNT(*) FROM canonical_config "
        "WHERE kind = 'config.document'), "
        "'config_paths', (SELECT COUNT(*) FROM canonical_config "
        "WHERE kind = 'config.path'), "
        "'config_references', (SELECT COUNT(*) FROM raw "
        "WHERE kind = 'config.reference'), "
        "'config_parse_errors', (SELECT COUNT(*) FROM raw "
        "WHERE kind = 'config.parse_error')), "
        "'safety', json_build_object("
        "'no_fetch', true, "
        "'no_api_calls', true, "
        "'no_tool_execution', true, "
        "'raw_profile_only', true, "
        "'no_new_canonical_namespaces', true)"
        ")::text;"
    )


def build_terraform_summary_query_sql(root_path: str) -> str:
    quoted_root = sql_literal(root_path)
    return (
        "WITH repo AS ("
        "SELECT id, name, root_path FROM repositories "
        f"WHERE repositories.root_path = {quoted_root}"
        "), "
        "raw AS ("
        "SELECT raw_observations.* FROM raw_observations "
        "JOIN repo ON repo.id = raw_observations.repository_id"
        "), "
        "terraform_raw AS ("
        "SELECT * FROM raw WHERE kind LIKE 'terraform.%'"
        "), "
        "terraform_files AS ("
        "SELECT * FROM terraform_raw WHERE kind = 'terraform.file'"
        "), "
        "terraform_refs AS ("
        "SELECT * FROM terraform_raw WHERE kind = 'terraform.reference'"
        "), "
        "terraform_redactions AS ("
        "SELECT * FROM terraform_raw WHERE kind = 'terraform.redaction'"
        "), "
        "canonical_config AS ("
        "SELECT canonical_nodes.* FROM canonical_nodes "
        "JOIN repo ON repo.id = canonical_nodes.repository_id "
        "WHERE canonical_nodes.graph_key_version = 1 "
        "AND canonical_nodes.kind IN ('config.document', 'config.path')"
        ") "
        "SELECT json_build_object("
        f"'root_path', {quoted_root}, "
        "'repository_name', (SELECT name FROM repo), "
        "'terraform_observations', (SELECT COUNT(*) FROM terraform_raw), "
        "'terraform_files', (SELECT COUNT(*) FROM terraform_files), "
        "'file_families', json_build_object("
        "'tf', (SELECT COUNT(*) FROM terraform_files "
        "WHERE payload_json->'metadata'->>'file_family' = 'tf'), "
        "'tfvars', (SELECT COUNT(*) FROM terraform_files "
        "WHERE payload_json->'metadata'->>'file_family' = 'tfvars' "
        "AND payload_json->>'path' NOT LIKE '%/terraform.tfvars' "
        "AND payload_json->>'path' <> 'terraform.tfvars' "
        "AND payload_json->>'path' NOT LIKE '%.auto.tfvars'), "
        "'terraform.tfvars', (SELECT COUNT(*) FROM terraform_files "
        "WHERE payload_json->>'path' = 'terraform.tfvars' "
        "OR payload_json->>'path' LIKE '%/terraform.tfvars'), "
        "'auto.tfvars', (SELECT COUNT(*) FROM terraform_files "
        "WHERE payload_json->>'path' LIKE '%.auto.tfvars')), "
        "'terraform', json_build_object("
        "'blocks', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.block'), "
        "'providers', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.provider'), "
        "'required_providers', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.required_provider'), "
        "'required_versions', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.required_version'), "
        "'backends', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.backend'), "
        "'resources', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.resource'), "
        "'data_sources', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.data_source'), "
        "'modules', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.module'), "
        "'variables', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.variable'), "
        "'outputs', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.output'), "
        "'locals', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.local'), "
        "'moved', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.moved'), "
        "'imports', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.import'), "
        "'checks', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.check'), "
        "'removed', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.removed')), "
        "'references', json_build_object("
        "'total', (SELECT COUNT(*) FROM terraform_refs), "
        "'provider_sources', (SELECT COUNT(*) FROM terraform_refs "
        "WHERE payload_json->'metadata'->>'reference_kind' = 'provider_source'), "
        "'version_constraints', (SELECT COUNT(*) FROM terraform_refs "
        "WHERE payload_json->'metadata'->>'reference_kind' = 'required_version') "
        "+ (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.required_provider' "
        "AND payload_json->'metadata'->>'version_constraint' IS NOT NULL), "
        "'module_sources', (SELECT COUNT(*) FROM terraform_refs "
        "WHERE payload_json->'metadata'->>'reference_kind' IN ("
        "'module_source', 'module_source_local')), "
        "'local_module_refs', (SELECT COUNT(*) FROM terraform_refs "
        "WHERE payload_json->'metadata'->>'reference_kind' = 'module_source_local'), "
        "'remote_refs_not_fetched', (SELECT COUNT(*) FROM terraform_refs "
        "WHERE COALESCE((payload_json->'metadata'->>'not_fetched')::boolean, false) "
        "AND payload_json->'metadata'->>'reference_kind' <> 'module_source_local'), "
        "'depends_on', (SELECT COUNT(*) FROM terraform_refs "
        "WHERE payload_json->'metadata'->>'reference_kind' = 'depends_on'), "
        "'provider_aliases', (SELECT COUNT(*) FROM terraform_refs "
        "WHERE payload_json->'metadata'->>'reference_kind' = 'provider_alias'), "
        "'repo_escape_diagnostics', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.parse_error' "
        "AND payload_json->'metadata'->>'error_kind' IN ("
        "'terraform-local-path-outside-root', 'terraform-repo-escape'))), "
        "'tfvars', json_build_object("
        "'files', (SELECT COUNT(*) FROM terraform_files "
        "WHERE payload_json->'metadata'->>'file_family' = 'tfvars'), "
        "'variables', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.variable' "
        "AND payload_json->'metadata'->>'profile' = 'terraform_tfvars'), "
        "'literal_values_exposed', false), "
        "'redactions', json_build_object("
        "'tfvars_values', (SELECT COUNT(*) FROM terraform_redactions "
        "WHERE payload_json->'metadata'->>'redaction_reason' = "
        "'tfvars-sensitive-by-default'), "
        "'secret_like_fields', (SELECT COUNT(*) FROM terraform_redactions "
        "WHERE payload_json->'metadata'->>'redaction_reason' IN ("
        "'secret-prone-terraform-attribute', "
        "'secret-prone-terraform-local', "
        "'secret-prone-key')), "
        "'credentialed_urls', (SELECT COUNT(*) FROM terraform_redactions "
        "WHERE payload_json->'metadata'->>'redaction_reason' IN ("
        "'credentialed-terraform-url', "
        "'credentialed-terraform-module-source')), "
        "'import_ids', (SELECT COUNT(*) FROM terraform_redactions "
        "WHERE payload_json->'metadata'->>'redaction_reason' = "
        "'terraform-import-id-sensitive-by-default'), "
        "'backend_values', (SELECT COUNT(*) FROM terraform_redactions "
        "WHERE payload_json->'metadata'->>'redaction_reason' = "
        "'secret-prone-terraform-attribute' "
        "AND payload_json->'metadata'->>'field_name' IN ("
        "'access_key', 'secret_key', 'token', 'password'))), "
        "'diagnostics', json_build_object("
        "'parse_errors', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.parse_error'), "
        "'limit_overflows', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.parse_error' "
        "AND payload_json->'metadata'->>'error_kind' LIKE '%limit%'), "
        "'malformed_hcl', (SELECT COUNT(*) FROM terraform_raw "
        "WHERE kind = 'terraform.parse_error' "
        "AND payload_json->'metadata'->>'error_kind' NOT LIKE '%limit%')), "
        "'generic_config', json_build_object("
        "'config_documents', (SELECT COUNT(*) FROM canonical_config "
        "WHERE kind = 'config.document'), "
        "'config_paths', (SELECT COUNT(*) FROM canonical_config "
        "WHERE kind = 'config.path'), "
        "'config_references', (SELECT COUNT(*) FROM raw "
        "WHERE kind = 'config.reference'), "
        "'file_nodes', (SELECT COUNT(*) FROM raw "
        "WHERE kind = 'file' "
        "AND payload_json->'metadata'->>'language' = 'terraform')), "
        "'safety', json_build_object("
        "'no_execution', true, "
        "'no_fetch', true, "
        "'no_terraform_cli', true, "
        "'no_provider_download', true, "
        "'no_module_download', true, "
        "'no_state_access', true, "
        "'tfvars_redacted', true, "
        "'raw_profile_only', true, "
        "'no_new_canonical_namespaces', true)"
        ")::text;"
    )


def build_bulk_summary_query_sql(root_path: str) -> str:
    quoted_root = sql_literal(root_path)
    return (
        "WITH repo AS ("
        "SELECT id, name, root_path FROM repositories "
        f"WHERE repositories.root_path = {quoted_root}"
        "), "
        "bulk_raw AS ("
        "SELECT raw_observations.* FROM raw_observations "
        "JOIN repo ON repo.id = raw_observations.repository_id "
        "WHERE raw_observations.payload_json->'metadata' ? 'bulk_run_id'"
        ") "
        "SELECT json_build_object("
        "'repository_name', (SELECT name FROM repo), "
        "'observations_with_bulk_provenance', (SELECT COUNT(*) FROM bulk_raw), "
        "'redacted_observations', (SELECT COUNT(*) FROM bulk_raw "
        "WHERE bulk_raw.payload_json->'metadata'->>'redacted' = 'true' "
        "OR bulk_raw.payload_json->'metadata' ? 'redaction_reason')"
        ")::text;"
    )


def build_api_summary_query_sql(root_path: str) -> str:
    quoted_root = sql_literal(root_path)
    return (
        "WITH repo AS ("
        "SELECT id, name, root_path FROM repositories "
        f"WHERE repositories.root_path = {quoted_root}"
        "), "
        "api_raw AS ("
        "SELECT raw_observations.* FROM raw_observations "
        "JOIN repo ON repo.id = raw_observations.repository_id "
        "WHERE raw_observations.payload_json->'metadata' ? 'api_run_id'"
        "), "
        "api_config_documents AS ("
        "SELECT DISTINCT canonical_nodes.canonical_key "
        "FROM canonical_nodes "
        "JOIN canonical_node_evidence "
        "ON canonical_node_evidence.canonical_node_id = canonical_nodes.id "
        "JOIN canonical_evidence "
        "ON canonical_evidence.id = "
        "canonical_node_evidence.canonical_evidence_id "
        "JOIN api_raw "
        "ON api_raw.id = canonical_evidence.raw_observation_id "
        "WHERE canonical_nodes.kind = 'config.document'"
        ") "
        "SELECT json_build_object("
        "'repository_name', (SELECT name FROM repo), "
        "'observations_with_api_provenance', (SELECT COUNT(*) FROM api_raw), "
        "'config_documents_from_api', "
        "(SELECT COUNT(*) FROM api_config_documents)"
        ")::text;"
    )
