"""SQL builders for RepoMap storage readback and load preparation."""

from __future__ import annotations

from repomap_kg.storage.sql_core import (
    canonical_file_path_prefix,
    positive_limit,
    require_supported_graph_key_version,
    sql_bool,
    sql_int_or_null,
    sql_like_prefix_literal,
    sql_literal,
)
from repomap_kg.storage.sql_canonical import (
    build_canonical_edge_query_sql,
    build_canonical_neighborhood_query_sql,
    build_canonical_node_query_sql,
    build_canonical_storage_summary_query_sql,
    build_explain_canonical_edge_query_sql,
)
from repomap_kg.storage.rows import (
    CanonicalLoadRows as CanonicalLoadRows,
    FileRow as FileRow,
    RawObservationRow as RawObservationRow,
)
from repomap_kg.storage.sql_load import (
    build_canonical_ingest_sql,
    canonical_edge_evidence_upsert_sql,
    canonical_edge_upsert_sql,
    canonical_evidence_upsert_sql,
    canonical_ingest_statements,
    canonical_load_summary_select_sql,
    canonical_node_evidence_upsert_sql,
    canonical_node_upsert_sql,
    file_load_summary_select_sql,
    file_upsert_sql,
    raw_observation_upsert_sql,
    repository_run_prefix_sql,
    run_completion_statements as run_completion_statements,
)
from repomap_kg.storage.sql_sources import (
    build_ingested_source_query_sql,
    build_source_feed_item_explanation_query_sql,
    build_source_feed_item_query_sql,
    build_source_reference_query_sql,
    build_source_run_query_sql,
    build_source_summary_query_sql,
    source_observations_cte,
)
from repomap_kg.storage.sql_summaries import (
    build_api_summary_query_sql,
    build_bulk_summary_query_sql,
    build_email_summary_query_sql,
    build_js_framework_summary_query_sql,
    build_js_summary_query_sql,
    build_nix_summary_query_sql,
    build_openapi_summary_query_sql,
    build_python_summary_query_sql,
    build_ruby_summary_query_sql,
    build_terraform_summary_query_sql,
)

__all__ = (
    "build_canonical_ingest_sql",
    "repository_run_prefix_sql",
    "canonical_ingest_statements",
    "file_load_summary_select_sql",
    "canonical_load_summary_select_sql",
    "build_canonical_node_query_sql",
    "build_canonical_edge_query_sql",
    "build_canonical_neighborhood_query_sql",
    "build_explain_canonical_edge_query_sql",
    "build_canonical_storage_summary_query_sql",
    "build_ruby_summary_query_sql",
    "build_js_summary_query_sql",
    "build_js_framework_summary_query_sql",
    "build_openapi_summary_query_sql",
    "build_terraform_summary_query_sql",
    "build_python_summary_query_sql",
    "build_nix_summary_query_sql",
    "build_ingested_source_query_sql",
    "build_email_summary_query_sql",
    "build_bulk_summary_query_sql",
    "build_api_summary_query_sql",
    "build_source_summary_query_sql",
    "build_source_run_query_sql",
    "build_source_feed_item_query_sql",
    "build_source_reference_query_sql",
    "build_source_feed_item_explanation_query_sql",
    "source_observations_cte",
    "positive_limit",
    "file_upsert_sql",
    "raw_observation_upsert_sql",
    "canonical_node_upsert_sql",
    "canonical_edge_upsert_sql",
    "canonical_evidence_upsert_sql",
    "canonical_node_evidence_upsert_sql",
    "canonical_edge_evidence_upsert_sql",
    "require_supported_graph_key_version",
    "canonical_file_path_prefix",
    "sql_like_prefix_literal",
    "sql_literal",
    "sql_bool",
    "sql_int_or_null",
)
