"""SQL builder for RepoMap Python storage summary readback."""

from __future__ import annotations

from repomap_kg.storage.sql_core import sql_literal

__all__ = ("build_python_summary_query_sql",)


def build_python_summary_query_sql(root_path: str) -> str:
    quoted_root = sql_literal(root_path)
    return (
        "WITH repo AS ("
        "SELECT id, name, root_path FROM repositories "
        f"WHERE repositories.root_path = {quoted_root}"
        "), "
        "raw AS ("
        "SELECT raw_observations.* FROM raw_observations "
        "JOIN repo ON repo.id = raw_observations.repository_id"
        "), "
        "python_raw AS ("
        "SELECT * FROM raw WHERE kind LIKE 'python.%'"
        "), "
        "python_refs AS ("
        "SELECT * FROM python_raw WHERE kind = 'python.reference'"
        "), "
        "python_redactions AS ("
        "SELECT * FROM python_raw WHERE kind = 'python.redaction'"
        "), "
        "python_errors AS ("
        "SELECT * FROM python_raw WHERE kind = 'python.parse_error'"
        "), "
        "canonical_python AS ("
        "SELECT canonical_nodes.* FROM canonical_nodes "
        "JOIN repo ON repo.id = canonical_nodes.repository_id "
        "WHERE canonical_nodes.graph_key_version = 1 "
        "AND canonical_nodes.kind IN ("
        "'python.module', 'python.class', 'python.function', 'python.method')"
        "), "
        "canonical_config AS ("
        "SELECT canonical_nodes.* FROM canonical_nodes "
        "JOIN repo ON repo.id = canonical_nodes.repository_id "
        "WHERE canonical_nodes.graph_key_version = 1 "
        "AND canonical_nodes.kind IN ('config.document', 'config.path')"
        ") "
        "SELECT json_build_object("
        f"'root_path', {quoted_root}, "
        "'repository_name', (SELECT name FROM repo), "
        "'python_observations', (SELECT COUNT(*) FROM python_raw), "
        "'package_files', json_build_object("
        "'requirements', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.package_file' "
        "AND (payload_json->'metadata'->>'file_family' LIKE 'requirements%' "
        "OR payload_json->'metadata'->>'source_format' = 'python-requirements')), "
        "'pyproject', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.pyproject')), "
        "'packaging', json_build_object("
        "'requirements', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.requirement'), "
        "'dependency_groups', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.dependency_group'), "
        "'build_systems', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.build_system'), "
        "'entry_points', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.entry_point'), "
        "'tool_configs', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.tool_config')), "
        "'tests', json_build_object("
        "'test_files', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.test_file'), "
        "'unittest_cases', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.unittest_case'), "
        "'pytest_tests', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.pytest_test'), "
        "'test_functions', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.test_function'), "
        "'test_methods', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.test_method'), "
        "'fixtures', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind IN ('python.test_fixture', 'python.pytest_fixture')), "
        "'parametrize', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.test_parametrize'), "
        "'assertions', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.test_assertion')), "
        "'frameworks', json_build_object("
        "'flask_apps', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.flask_app'), "
        "'flask_blueprints', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.flask_blueprint'), "
        "'flask_routes', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.flask_route'), "
        "'fastapi_apps', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.fastapi_app'), "
        "'fastapi_routers', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.fastapi_router'), "
        "'fastapi_routes', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.fastapi_route'), "
        "'fastapi_dependencies', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.fastapi_dependency'), "
        "'django_projects', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.django_project'), "
        "'django_apps', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.django_app'), "
        "'django_urlpatterns', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.django_urlpattern'), "
        "'django_views', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.django_view'), "
        "'django_models', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.django_model'), "
        "'django_setting_references', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.django_setting_reference')), "
        "'references', json_build_object("
        "'total', (SELECT COUNT(*) FROM python_refs), "
        "'package_refs', (SELECT COUNT(*) FROM python_refs "
        "WHERE payload_json->'metadata'->>'source_format' IN ("
        "'python-requirements', 'pyproject.toml') "
        "OR payload_json->'metadata'->>'reference_kind' IN ("
        "'include_file', 'constraint_file', 'direct_url', 'vcs_url', "
        "'editable_local_path', 'local_path', 'index_url', "
        "'extra_index_url', 'find_links')), "
        "'local_file_refs', (SELECT COUNT(*) FROM python_refs "
        "WHERE payload_json->>'target' LIKE 'file:%' "
        "OR payload_json->'metadata'->>'resolution' = 'local'), "
        "'direct_urls_not_fetched', (SELECT COUNT(*) FROM python_refs "
        "WHERE COALESCE((payload_json->'metadata'->>'not_fetched')::boolean, false) "
        "AND (payload_json->'metadata'->>'reference_kind' IN ("
        "'direct_url', 'vcs_url', 'dependency_url') "
        "OR COALESCE((payload_json->'metadata'->>'direct_url')::boolean, false))), "
        "'index_urls_not_fetched', (SELECT COUNT(*) FROM python_refs "
        "WHERE COALESCE((payload_json->'metadata'->>'not_fetched')::boolean, false) "
        "AND payload_json->'metadata'->>'reference_kind' IN ("
        "'index_url', 'extra_index_url', 'find_links')), "
        "'framework_refs', (SELECT COUNT(*) FROM python_refs "
        "WHERE payload_json->'metadata'->>'framework' IN ("
        "'flask', 'fastapi', 'django'))), "
        "'redactions', json_build_object("
        "'credentialed_urls', (SELECT COUNT(*) FROM python_redactions "
        "WHERE payload_json->'metadata'->>'redaction_reason' LIKE '%credential%'), "
        "'private_indexes', (SELECT COUNT(*) FROM python_redactions "
        "WHERE payload_json->'metadata'->>'redaction_reason' LIKE '%index%'), "
        "'secret_like_config', (SELECT COUNT(*) FROM python_redactions "
        "WHERE payload_json->'metadata'->>'redaction_reason' LIKE '%secret%'), "
        "'framework_settings', (SELECT COUNT(*) FROM python_redactions "
        "WHERE payload_json->'metadata'->>'framework' IN ("
        "'flask', 'fastapi', 'django') "
        "OR payload_json->'metadata'->>'redaction_reason' LIKE '%django%' "
        "OR payload_json->'metadata'->>'redaction_reason' LIKE '%flask%' "
        "OR payload_json->'metadata'->>'redaction_reason' LIKE '%fastapi%')), "
        "'diagnostics', json_build_object("
        "'parse_errors', (SELECT COUNT(*) FROM python_errors), "
        "'limit_overflows', (SELECT COUNT(*) FROM python_errors "
        "WHERE payload_json->'metadata'->>'error_kind' LIKE '%limit%'), "
        "'dynamic_constructs', (SELECT COUNT(*) FROM python_errors "
        "WHERE COALESCE((payload_json->'metadata'->>'dynamic')::boolean, false) "
        "OR payload_json->'metadata'->>'error_kind' LIKE 'dynamic-%')), "
        "'generic_python', json_build_object("
        "'modules', (SELECT COUNT(*) FROM canonical_python "
        "WHERE kind = 'python.module'), "
        "'classes', (SELECT COUNT(*) FROM canonical_python "
        "WHERE kind = 'python.class'), "
        "'functions', (SELECT COUNT(*) FROM canonical_python "
        "WHERE kind = 'python.function'), "
        "'methods', (SELECT COUNT(*) FROM canonical_python "
        "WHERE kind = 'python.method'), "
        "'imports', (SELECT COUNT(*) FROM python_raw "
        "WHERE kind = 'python.import')), "
        "'generic_config', json_build_object("
        "'config_documents', (SELECT COUNT(*) FROM canonical_config "
        "WHERE kind = 'config.document'), "
        "'config_paths', (SELECT COUNT(*) FROM canonical_config "
        "WHERE kind = 'config.path'), "
        "'config_references', (SELECT COUNT(*) FROM raw "
        "WHERE kind = 'config.reference')), "
        "'dogfooding', json_build_object("
        "'repo_map_profile_observed', EXISTS (SELECT 1 FROM python_raw "
        "WHERE kind IN ('python.pyproject', 'python.package_file', 'python.test_file') "
        "AND (payload_json->'metadata'->>'project_name' LIKE 'repo-map%' "
        "OR payload_json->>'name' LIKE 'repo-map%' "
        "OR payload_json->>'path' LIKE '%repomap_kg%')), "
        "'bounded', true, "
        "'generated_report_committed', false), "
        "'safety', json_build_object("
        "'no_execution', true, "
        "'no_imports', true, "
        "'no_test_execution', true, "
        "'no_framework_startup', true, "
        "'no_fetch', true, "
        "'no_package_install', true, "
        "'no_openapi_fetch', true, "
        "'raw_profile_only', true, "
        "'no_new_canonical_namespaces', true)"
        ")::text;"
    )
