"""SQL builder for RepoMap Nix storage summary readback."""

from __future__ import annotations

from repomap_kg.storage.graph_readback_sql import build_repository_filter_sql

__all__ = ("build_nix_summary_query_sql",)


def build_nix_summary_query_sql(
    root_path: str,
    repository_identity: str | None = None,
) -> str:
    repo_filter = build_repository_filter_sql(root_path, repository_identity)
    return (
        "WITH repo AS ("
        "SELECT id, name, root_path FROM repositories "
        f"WHERE {repo_filter}"
        "), "
        "raw AS ("
        "SELECT raw_observations.* FROM raw_observations "
        "JOIN repo ON repo.id = raw_observations.repository_id"
        "), "
        "nix_raw AS ("
        "SELECT * FROM raw WHERE kind LIKE 'nix.%'"
        "), "
        "nix_outputs AS ("
        "SELECT * FROM nix_raw WHERE kind IN ("
        "'nix.app', 'nix.package', 'nix.devShell', 'nix.check')"
        "), "
        "observed_flake_files AS ("
        "SELECT DISTINCT path FROM raw "
        "WHERE kind = 'file' "
        "AND regexp_replace(path, '^.*/', '') = 'flake.nix' "
        "AND (payload_json->'metadata'->>'language' = 'nix' "
        "OR payload_json->'metadata'->>'language' IS NULL)"
        "), "
        "flake_output_files AS ("
        "SELECT DISTINCT path FROM nix_outputs "
        "WHERE path IS NOT NULL AND path <> ''"
        "), "
        "nix_imports AS ("
        "SELECT * FROM nix_raw WHERE kind = 'nix.import'"
        "), "
        "nix_path_refs AS ("
        "SELECT * FROM nix_raw WHERE kind = 'nix.path_ref'"
        "), "
        "nix_apps AS ("
        "SELECT * FROM nix_raw WHERE kind = 'nix.app'"
        "), "
        "nix_flake_inputs AS ("
        "SELECT * FROM nix_raw WHERE kind = 'nix.flake_input'"
        "), "
        "nix_output_sections AS ("
        "SELECT * FROM nix_raw WHERE kind = 'nix.output_section'"
        "), "
        "nix_dynamic_output_shapes AS ("
        "SELECT * FROM nix_raw WHERE kind = 'nix.dynamic_output_shape'"
        "), "
        "nix_unsupported_flake_shapes AS ("
        "SELECT * FROM nix_raw WHERE kind = 'nix.unsupported_flake_shape'"
        "), "
        "canonical_nix AS ("
        "SELECT canonical_nodes.* FROM canonical_nodes "
        "JOIN repo ON repo.id = canonical_nodes.repository_id "
        "WHERE canonical_nodes.graph_key_version = 1 "
        "AND canonical_nodes.kind IN ("
        "'nix.app', 'nix.package', 'nix.devShell', 'nix.check')"
        "), "
        "canonical_nix_output_sections AS ("
        "SELECT DISTINCT canonical_nodes.* FROM canonical_nodes "
        "JOIN repo ON repo.id = canonical_nodes.repository_id "
        "JOIN canonical_node_evidence "
        "ON canonical_node_evidence.canonical_node_id = canonical_nodes.id "
        "JOIN canonical_evidence "
        "ON canonical_evidence.id = canonical_node_evidence.canonical_evidence_id "
        "WHERE canonical_nodes.graph_key_version = 1 "
        "AND canonical_nodes.kind = 'nix.output' "
        "AND canonical_evidence.raw_kind = 'nix.output_section'"
        "), "
        "canonical_nix_edge_evidence AS ("
        "SELECT DISTINCT canonical_edges.id, canonical_edges.edge_kind, "
        "canonical_evidence.raw_kind "
        "FROM canonical_edges "
        "JOIN repo ON repo.id = canonical_edges.repository_id "
        "JOIN canonical_edge_evidence "
        "ON canonical_edge_evidence.canonical_edge_id = canonical_edges.id "
        "JOIN canonical_evidence "
        "ON canonical_evidence.id = canonical_edge_evidence.canonical_evidence_id "
        "WHERE canonical_edges.graph_key_version = 1 "
        "AND canonical_evidence.raw_kind LIKE 'nix.%'"
        "), "
        "canonical_config AS ("
        "SELECT canonical_nodes.* FROM canonical_nodes "
        "JOIN repo ON repo.id = canonical_nodes.repository_id "
        "WHERE canonical_nodes.graph_key_version = 1 "
        "AND canonical_nodes.kind IN ('config.document', 'config.path')"
        ") "
        "SELECT json_build_object("
        "'root_path', '[root-path]', "
        "'repository_name', (SELECT name FROM repo), "
        "'nix_observations', (SELECT COUNT(*) FROM nix_raw), "
        "'nix_files', (SELECT COUNT(*) FROM raw "
        "WHERE kind = 'file' "
        "AND payload_json->'metadata'->>'language' = 'nix'), "
        "'flake_files', (SELECT COUNT(*) FROM observed_flake_files), "
        "'raw', json_build_object("
        "'imports', (SELECT COUNT(*) FROM nix_imports), "
        "'path_refs', (SELECT COUNT(*) FROM nix_path_refs), "
        "'apps', (SELECT COUNT(*) FROM nix_raw WHERE kind = 'nix.app'), "
        "'packages', (SELECT COUNT(*) FROM nix_raw WHERE kind = 'nix.package'), "
        "'dev_shells', (SELECT COUNT(*) FROM nix_raw "
        "WHERE kind = 'nix.devShell'), "
        "'checks', (SELECT COUNT(*) FROM nix_raw WHERE kind = 'nix.check')), "
        "'canonical', json_build_object("
        "'apps', (SELECT COUNT(*) FROM canonical_nix WHERE kind = 'nix.app'), "
        "'packages', (SELECT COUNT(*) FROM canonical_nix "
        "WHERE kind = 'nix.package'), "
        "'dev_shells', (SELECT COUNT(*) FROM canonical_nix "
        "WHERE kind = 'nix.devShell'), "
        "'checks', (SELECT COUNT(*) FROM canonical_nix WHERE kind = 'nix.check'), "
        "'output_sections', (SELECT COUNT(*) "
        "FROM canonical_nix_output_sections)), "
        "'edges', json_build_object("
        "'import_sources', (SELECT COUNT(*) FROM canonical_nix_edge_evidence "
        "WHERE edge_kind = 'sources' AND raw_kind = 'nix.import'), "
        "'output_defines', (SELECT COUNT(*) FROM canonical_nix_edge_evidence "
        "WHERE edge_kind = 'defines' "
        "AND raw_kind IN ('nix.app', 'nix.package', 'nix.devShell', 'nix.check')), "
        "'output_section_defines', (SELECT COUNT(*) "
        "FROM canonical_nix_edge_evidence "
        "WHERE edge_kind = 'defines' AND raw_kind = 'nix.output_section'), "
        "'app_program_edges', (SELECT COUNT(*) FROM canonical_nix_edge_evidence "
        "WHERE edge_kind = 'exposes_script' AND raw_kind = 'nix.app')), "
        "'programs', json_build_object("
        "'app_programs_total', (SELECT COUNT(*) FROM nix_apps "
        "WHERE payload_json->'metadata'->>'program_resolution' IS NOT NULL "
        "OR payload_json->'metadata' ? 'program'), "
        "'local', (SELECT COUNT(*) FROM nix_apps "
        "WHERE payload_json->'metadata'->>'program_resolution' = 'local'), "
        "'dynamic', (SELECT COUNT(*) FROM nix_apps "
        "WHERE payload_json->'metadata'->>'program_resolution' = 'dynamic'), "
        "'external', (SELECT COUNT(*) FROM nix_apps "
        "WHERE payload_json->'metadata'->>'program_resolution' = 'external'), "
        "'unknown', (SELECT COUNT(*) FROM nix_apps "
        "WHERE payload_json->'metadata'->>'program_resolution' = 'unknown')), "
        "'paths', json_build_object("
        "'path_refs_total', (SELECT COUNT(*) FROM nix_path_refs), "
        "'local', (SELECT COUNT(*) FROM nix_path_refs "
        "WHERE payload_json->'metadata'->>'resolution' = 'local'), "
        "'dynamic', (SELECT COUNT(*) FROM nix_path_refs "
        "WHERE payload_json->'metadata'->>'resolution' = 'dynamic'), "
        "'unknown', (SELECT COUNT(*) FROM nix_path_refs "
        "WHERE payload_json->'metadata'->>'resolution' = 'unknown'), "
        "'repo_escaping_or_rejected', (SELECT COUNT(*) FROM nix_path_refs "
        "WHERE payload_json->>'target' LIKE 'unknown:file:%' "
        "OR payload_json->'metadata'->>'resolution' IN ("
        "'repo-escaping', 'rejected') "
        "OR payload_json->'metadata'->>'resolution_reason' LIKE 'repo-escaping%')), "
        "'flake_inputs', json_build_object("
        "'total', (SELECT COUNT(*) FROM nix_flake_inputs), "
        "'with_url', (SELECT COUNT(*) FROM nix_flake_inputs "
        "WHERE payload_json->'metadata'->>'has_url' = 'true'), "
        "'with_follows', (SELECT COUNT(*) FROM nix_flake_inputs "
        "WHERE payload_json->'metadata'->>'has_follows' = 'true'), "
        "'redacted_sources', (SELECT COUNT(*) FROM nix_flake_inputs "
        "WHERE payload_json->'metadata'->>'source_redacted' = 'true'), "
        "'source_types', json_build_object("
        "'github', (SELECT COUNT(*) FROM nix_flake_inputs "
        "WHERE payload_json->'metadata'->>'source_type' = 'github'), "
        "'git', (SELECT COUNT(*) FROM nix_flake_inputs "
        "WHERE payload_json->'metadata'->>'source_type' = 'git'), "
        "'path', (SELECT COUNT(*) FROM nix_flake_inputs "
        "WHERE payload_json->'metadata'->>'source_type' = 'path'), "
        "'tarball', (SELECT COUNT(*) FROM nix_flake_inputs "
        "WHERE payload_json->'metadata'->>'source_type' = 'tarball'), "
        "'follows', (SELECT COUNT(*) FROM nix_flake_inputs "
        "WHERE payload_json->'metadata'->>'source_type' = 'follows'), "
        "'unknown', (SELECT COUNT(*) FROM nix_flake_inputs "
        "WHERE payload_json->'metadata'->>'source_type' = 'unknown'), "
        "'dynamic', (SELECT COUNT(*) FROM nix_flake_inputs "
        "WHERE payload_json->'metadata'->>'source_type' = 'dynamic'))), "
        "'output_sections', json_build_object("
        "'total', (SELECT COUNT(*) FROM nix_output_sections), "
        "'by_section', json_build_object("
        "'packages', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'section' = 'packages'), "
        "'apps', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'section' = 'apps'), "
        "'devShells', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'section' = 'devShells'), "
        "'checks', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'section' = 'checks'), "
        "'nixosModules', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'section' = 'nixosModules'), "
        "'darwinModules', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'section' = 'darwinModules'), "
        "'homeManagerModules', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'section' = 'homeManagerModules'), "
        "'overlays', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'section' = 'overlays'), "
        "'formatter', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'section' = 'formatter'), "
        "'templates', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'section' = 'templates'), "
        "'legacyPackages', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'section' = 'legacyPackages')), "
        "'by_family', json_build_object("
        "'output', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'section_family' = 'output'), "
        "'module', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'section_family' = 'module'), "
        "'overlay', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'section_family' = 'overlay'), "
        "'formatter', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'section_family' = 'formatter'), "
        "'template', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'section_family' = 'template'), "
        "'legacy_package', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'section_family' = "
        "'legacy_package')), "
        "'by_shape', json_build_object("
        "'direct_assignment', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'shape' = 'direct_assignment'), "
        "'nested_attrset', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'shape' = 'nested_attrset'), "
        "'inherit', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'shape' = 'inherit'), "
        "'merged_attrset', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'shape' = 'merged_attrset'), "
        "'dynamic', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'shape' = 'dynamic'), "
        "'helper_framework', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'shape' = 'helper_framework'), "
        "'unknown', (SELECT COUNT(*) FROM nix_output_sections "
        "WHERE payload_json->'metadata'->>'shape' = 'unknown'))), "
        "'dynamic_output_shapes', json_build_object("
        "'total', (SELECT COUNT(*) FROM nix_dynamic_output_shapes), "
        "'by_pattern', json_build_object("
        "'eachDefaultSystem', (SELECT COUNT(*) FROM nix_dynamic_output_shapes "
        "WHERE payload_json->'metadata'->>'pattern' = 'eachDefaultSystem'), "
        "'genAttrs', (SELECT COUNT(*) FROM nix_dynamic_output_shapes "
        "WHERE payload_json->'metadata'->>'pattern' = 'genAttrs'), "
        "'forAllSystems', (SELECT COUNT(*) FROM nix_dynamic_output_shapes "
        "WHERE payload_json->'metadata'->>'pattern' = 'forAllSystems'), "
        "'flake-utils', (SELECT COUNT(*) FROM nix_dynamic_output_shapes "
        "WHERE payload_json->'metadata'->>'pattern' = 'flake-utils'), "
        "'flake-parts', (SELECT COUNT(*) FROM nix_dynamic_output_shapes "
        "WHERE payload_json->'metadata'->>'pattern' = 'flake-parts'), "
        "'string_interpolation', (SELECT COUNT(*) "
        "FROM nix_dynamic_output_shapes "
        "WHERE payload_json->'metadata'->>'pattern' = "
        "'string_interpolation'))), "
        "'unsupported_flake_shapes', json_build_object("
        "'total', (SELECT COUNT(*) FROM nix_unsupported_flake_shapes), "
        "'by_pattern', json_build_object("
        "'imported_outputs', (SELECT COUNT(*) "
        "FROM nix_unsupported_flake_shapes "
        "WHERE payload_json->'metadata'->>'pattern' = 'imported_outputs'), "
        "'merged_attrset', (SELECT COUNT(*) "
        "FROM nix_unsupported_flake_shapes "
        "WHERE payload_json->'metadata'->>'pattern' = 'merged_attrset'), "
        "'inherit_outputs', (SELECT COUNT(*) "
        "FROM nix_unsupported_flake_shapes "
        "WHERE payload_json->'metadata'->>'pattern' = 'inherit_outputs'), "
        "'nested_attrset_without_direct_identity', (SELECT COUNT(*) "
        "FROM nix_unsupported_flake_shapes "
        "WHERE payload_json->'metadata'->>'pattern' = "
        "'nested_attrset_without_direct_identity'), "
        "'template_section', (SELECT COUNT(*) "
        "FROM nix_unsupported_flake_shapes "
        "WHERE payload_json->'metadata'->>'pattern' = 'template_section'), "
        "'legacy_packages_section', (SELECT COUNT(*) "
        "FROM nix_unsupported_flake_shapes "
        "WHERE payload_json->'metadata'->>'pattern' = "
        "'legacy_packages_section'), "
        "'unknown_dynamic', (SELECT COUNT(*) "
        "FROM nix_unsupported_flake_shapes "
        "WHERE payload_json->'metadata'->>'pattern' = 'unknown_dynamic'))), "
        "'generic_config', json_build_object("
        "'config_documents', (SELECT COUNT(*) FROM canonical_config "
        "WHERE kind = 'config.document'), "
        "'config_paths', (SELECT COUNT(*) FROM canonical_config "
        "WHERE kind = 'config.path'), "
        "'config_references', (SELECT COUNT(*) FROM raw "
        "WHERE kind = 'config.reference'), "
        "'config_parse_errors', (SELECT COUNT(*) FROM raw "
        "WHERE kind = 'config.parse_error'), "
        "'config_redactions', (SELECT COUNT(*) FROM raw "
        "WHERE kind = 'config.redaction' "
        "OR (kind = 'config.path' "
        "AND COALESCE((payload_json->'metadata'->>'redacted')::boolean, false)))), "
        "'diagnostics', json_build_object("
        "'missing_output_identity', (SELECT COUNT(*) FROM nix_outputs "
        "WHERE COALESCE(payload_json->'metadata'->>'flake_ref', '') = '' "
        "OR COALESCE(payload_json->'metadata'->>'system', '') = '' "
        "OR COALESCE(payload_json->'metadata'->>'name', '') = ''), "
        "'dynamic_imports', (SELECT COUNT(*) FROM nix_imports "
        "WHERE COALESCE((payload_json->'metadata'->>'dynamic')::boolean, false) "
        "OR payload_json->'metadata'->>'resolution' = 'dynamic' "
        "OR payload_json->'metadata'->>'dynamic_reason' IS NOT NULL), "
        "'unknown_imports', (SELECT COUNT(*) FROM nix_imports "
        "WHERE payload_json->>'target' LIKE 'unknown:%' "
        "OR payload_json->'metadata'->>'resolution' = 'unknown'), "
        "'unknown_app_programs', (SELECT COUNT(*) FROM nix_apps "
        "WHERE payload_json->'metadata'->>'program_resolution' = 'unknown'), "
        "'raw_only_path_refs', (SELECT COUNT(*) FROM nix_path_refs), "
        "'flake_files_without_output_observations', (SELECT COUNT(*) "
        "FROM observed_flake_files "
        "WHERE NOT EXISTS (SELECT 1 FROM flake_output_files "
        "WHERE flake_output_files.path = observed_flake_files.path))), "
        "'limitations', json_build_object("
        "'flake_inputs_not_extracted', false, "
        "'overlays_not_extracted', true, "
        "'modules_not_classified', true, "
        "'packages_are_static_attr_counts_only', true, "
        "'no_nix_eval', true, "
        "'no_flake_lock_resolution', true, "
        "'path_values_omitted', true, "
        "'weak_output_sections_are_not_concrete_outputs', true), "
        "'safety', json_build_object("
        "'read_only', true, "
        "'no_execution', true, "
        "'no_nix_cli', true, "
        "'no_fetch', true, "
        "'no_flake_lock_resolution', true, "
        "'no_store_inspection', true, "
        "'no_path_values', true, "
        "'private_paths_redacted', true, "
        "'raw_profile_only', true)"
        ")::text;"
    )
