"""Linux systemd per-user adapter for the portable service contract."""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from pathlib import Path

from repomap_kg.service_package.contract import (
    ServicePackageSpec,
    is_recognizable_psql_reference,
    is_recognizable_python_reference,
    service_semantics,
)


_MAX_DEFINITION_BYTES = 1024 * 1024
_MARKER = "# Generated by RepoMap service package v1"
_IDENTITY = "org.repomap.coordinator"
_UNIT_NAME = "repomap-coordinator.service"
_QUOTED_TOKEN_RE = re.compile(r'"(?:\\.|[^"\\])*"')


@dataclass(frozen=True)
class SystemdUserAdapter:
    """Translate one common specification into a systemd user unit."""

    user_home: Path
    uid: int
    platform_name: str = "linux"
    artifact_kind: str = "systemd_user_unit"

    @property
    def target_path(self) -> Path:
        return self.user_home / ".config" / "systemd" / "user" / _UNIT_NAME

    def render(self, spec: ServicePackageSpec) -> bytes:
        return _render_unit(
            foreground_argv=spec.foreground_argv,
            working_directory=spec.working_directory,
            stdout_path=spec.stdout_path,
            stderr_path=spec.stderr_path,
            service_identity=spec.service_identity,
            python_sha256=spec.python_sha256,
            psql_sha256=spec.psql_sha256,
            restart_delay_seconds=spec.restart_delay_seconds,
            shutdown_timeout_seconds=spec.shutdown_timeout_seconds,
        )

    def validate(self, content: bytes, spec: ServicePackageSpec) -> None:
        if not self.recognizes(content) or content != self.render(spec):
            raise ValueError("service_definition_invalid")

    def recognizes(self, content: bytes) -> bool:
        if not isinstance(content, bytes) or len(content) > _MAX_DEFINITION_BYTES:
            return False
        try:
            text = content.decode("utf-8")
            argv = decode_systemd_exec_argv(content)
            python_sha256 = _metadata_value(text, "X-RepoMap-Python-SHA256")
            psql_sha256 = _metadata_value(text, "X-RepoMap-Psql-SHA256")
        except (UnicodeDecodeError, ValueError):
            return False
        if not text.startswith(f"{_MARKER}\n"):
            return False
        if f"X-RepoMap-Service-Identity={_IDENTITY}\n" not in text:
            return False
        if "X-RepoMap-Service-Package=1\n" not in text:
            return False
        if "\nEnvironment=" in text or "\nEnvironmentFile=" in text:
            return False
        if not _recognized_foreground_argv(argv, python_sha256, psql_sha256):
            return False
        home = Path(argv[6])
        runtime_directory = home / "coordinator"
        expected = _render_unit(
            foreground_argv=argv,
            working_directory=home,
            stdout_path=runtime_directory / "service.stdout.log",
            stderr_path=runtime_directory / "service.stderr.log",
            service_identity=_IDENTITY,
            python_sha256=python_sha256,
            psql_sha256=psql_sha256,
            restart_delay_seconds=10,
            shutdown_timeout_seconds=30,
        )
        return content == expected

    def semantic_values(self, spec: ServicePackageSpec) -> dict[str, object]:
        return service_semantics(spec)

    def active_probe_argv(self) -> tuple[str, ...]:
        return (
            "/usr/bin/systemctl",
            "--user",
            "is-active",
            "--quiet",
            _UNIT_NAME,
        )

    def manager_probe_argv(self) -> tuple[str, ...]:
        return ("/usr/bin/systemctl", "--user", "show-environment")

    def inactive_return_codes(self) -> frozenset[int]:
        return frozenset({3})

    def disabled_return_codes(self) -> frozenset[int]:
        return frozenset({1})

    def enabled_probe_argv(self) -> tuple[str, ...]:
        return (
            "/usr/bin/systemctl",
            "--user",
            "is-enabled",
            "--quiet",
            _UNIT_NAME,
        )

    def reload_commands(self) -> tuple[tuple[str, ...], ...]:
        return (("/usr/bin/systemctl", "--user", "daemon-reload"),)

    def enable_commands(self) -> tuple[tuple[str, ...], ...]:
        return (("/usr/bin/systemctl", "--user", "enable", _UNIT_NAME),)

    def disable_commands(self) -> tuple[tuple[str, ...], ...]:
        return (("/usr/bin/systemctl", "--user", "disable", _UNIT_NAME),)

    def start_commands(self) -> tuple[tuple[str, ...], ...]:
        return (("/usr/bin/systemctl", "--user", "start", _UNIT_NAME),)

    def stop_commands(self) -> tuple[tuple[str, ...], ...]:
        return (("/usr/bin/systemctl", "--user", "stop", _UNIT_NAME),)

    def restart_commands(self) -> tuple[tuple[str, ...], ...]:
        return (("/usr/bin/systemctl", "--user", "restart", _UNIT_NAME),)


def _render_unit(
    *,
    foreground_argv: tuple[str, ...],
    working_directory: Path,
    stdout_path: Path,
    stderr_path: Path,
    service_identity: str,
    python_sha256: str | None,
    psql_sha256: str | None,
    restart_delay_seconds: int,
    shutdown_timeout_seconds: int,
) -> bytes:
    exec_start = " ".join(
        _quote_systemd_exec_token(value) for value in foreground_argv
    )
    lines = [
        _MARKER,
        "[Unit]",
        "Description=RepoMap foreground coordinator",
        f"X-RepoMap-Service-Identity={service_identity}",
        "X-RepoMap-Service-Package=1",
        f"X-RepoMap-Python-SHA256={python_sha256}",
        f"X-RepoMap-Psql-SHA256={psql_sha256}",
        "",
        "[Service]",
        "Type=simple",
        f"ExecStart={exec_start}",
        f"WorkingDirectory={_quote_systemd_scalar(str(working_directory))}",
        "Restart=on-failure",
        f"RestartSec={restart_delay_seconds}s",
        "KillSignal=SIGTERM",
        f"TimeoutStopSec={shutdown_timeout_seconds}s",
        "UMask=0077",
        f"StandardOutput={_quote_systemd_scalar(f'append:{stdout_path}')}",
        f"StandardError={_quote_systemd_scalar(f'append:{stderr_path}')}",
        "",
        "[Install]",
        "WantedBy=default.target",
        "",
    ]
    return "\n".join(lines).encode("utf-8")


def decode_systemd_exec_argv(content: bytes) -> tuple[str, ...]:
    """Decode the closed quoted ExecStart format emitted by this adapter."""

    if len(content) > _MAX_DEFINITION_BYTES:
        raise ValueError("service_definition_invalid")
    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError:
        raise ValueError("service_definition_invalid") from None
    lines = [line[len("ExecStart=") :] for line in text.splitlines() if line.startswith("ExecStart=")]
    if len(lines) != 1:
        raise ValueError("service_definition_invalid")
    encoded = lines[0]
    matches = list(_QUOTED_TOKEN_RE.finditer(encoded))
    if not matches:
        raise ValueError("service_definition_invalid")
    cursor = 0
    values: list[str] = []
    for match in matches:
        if encoded[cursor : match.start()].strip():
            raise ValueError("service_definition_invalid")
        values.append(_decode_systemd_value(match.group()[1:-1]))
        cursor = match.end()
    if encoded[cursor:].strip():
        raise ValueError("service_definition_invalid")
    return tuple(values)


def _quote_systemd_exec_token(value: str) -> str:
    if any(character in value for character in ("\x00", "\n", "\r")):
        raise ValueError("service_definition_value_invalid")
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "$$")
        .replace("%", "%%")
    )
    return f'"{escaped}"'


def _quote_systemd_scalar(value: str) -> str:
    if any(character in value for character in ("\x00", "\n", "\r")):
        raise ValueError("service_definition_value_invalid")
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("%", "%%")
    return f'"{escaped}"'


def _decode_systemd_value(value: str) -> str:
    decoded: list[str] = []
    index = 0
    while index < len(value):
        character = value[index]
        if character == "\\":
            index += 1
            if index >= len(value):
                raise ValueError("service_definition_invalid")
            decoded.append(value[index])
        elif character in {"$", "%"}:
            if index + 1 >= len(value) or value[index + 1] != character:
                raise ValueError("service_definition_invalid")
            decoded.append(character)
            index += 1
        else:
            decoded.append(character)
        index += 1
    return "".join(decoded)


def _recognized_foreground_argv(
    value: tuple[str, ...],
    python_sha256: str,
    psql_sha256: str,
) -> bool:
    if len(value) != 11 or not is_recognizable_python_reference(
        value[0], python_sha256
    ):
        return False
    if any("\x00" in item or "\n" in item or "\r" in item for item in value):
        return False
    return (
        value[1:6]
        == (
            "-m",
            "repomap_kg",
            "ops",
            "coordinator-serve",
            "--repo-map-home",
        )
        and os.path.isabs(value[6])
        and value[7:9]
        == ("--service-package-environment", "--service-package-psql")
        and is_recognizable_psql_reference(value[9], psql_sha256)
        and value[10] == "--json"
    )


def _metadata_value(text: str, name: str) -> str:
    prefix = f"{name}="
    values = [line[len(prefix) :] for line in text.splitlines() if line.startswith(prefix)]
    if len(values) != 1:
        raise ValueError("service_definition_invalid")
    return values[0]


__all__ = ["SystemdUserAdapter", "decode_systemd_exec_argv"]
