"""SQL builders for RepoMap operations refresh readback."""

from __future__ import annotations

from typing import Sequence

from repomap_kg.storage.sql_core import sql_literal


def build_refresh_status_sql(graphs: Sequence[tuple[str, str]]) -> str:
    if graphs:
        values = ", ".join(
            f"({sql_literal(graph_id)}, {sql_literal(repository_name)})"
            for graph_id, repository_name in graphs
        )
        configured = f"configured(graph_id, repository_name) AS (VALUES {values})"
    else:
        configured = (
            "configured(graph_id, repository_name) AS ("
            "SELECT NULL::text AS graph_id, NULL::text AS repository_name WHERE false)"
        )
    return (
        f"WITH {configured}, "
        "repo AS ("
        "SELECT configured.graph_id, configured.repository_name, "
        "repositories.id AS repository_id "
        "FROM configured "
        "LEFT JOIN repositories "
        "ON repositories.name = configured.repository_name"
        "), "
        "latest_recorded_run AS ("
        "SELECT DISTINCT ON (repo.graph_id) "
        "repo.graph_id, runs.* "
        "FROM repo "
        "JOIN runs ON runs.repository_id = repo.repository_id "
        "ORDER BY repo.graph_id, runs.id DESC"
        "), "
        "latest_portable_publication AS ("
        "SELECT DISTINCT ON (repo.graph_id) repo.graph_id, runs.* "
        "FROM repo JOIN runs ON runs.repository_id = repo.repository_id "
        "WHERE runs.status = 'complete' AND runs.execution_route IS NOT NULL "
        "ORDER BY repo.graph_id, runs.id DESC"
        ") "
        "SELECT json_build_object("
        "'graphs', COALESCE(json_agg(json_build_object("
        "'graph_id', repo.graph_id, "
        "'repository_name', repo.repository_name, "
        "'repository_exists', repo.repository_id IS NOT NULL, "
        "'latest_run_id', (SELECT id FROM latest_recorded_run "
        "WHERE graph_id = repo.graph_id), "
        "'latest_run_status', (SELECT status FROM latest_recorded_run "
        "WHERE graph_id = repo.graph_id), "
        "'latest_run_started_at', (SELECT to_char(started_at AT TIME ZONE 'UTC', "
        "'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"') FROM latest_recorded_run "
        "WHERE graph_id = repo.graph_id), "
        "'latest_run_finished_at', (SELECT to_char(finished_at AT TIME ZONE 'UTC', "
        "'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"') FROM latest_recorded_run "
        "WHERE graph_id = repo.graph_id), "
        "'publication', (SELECT json_build_object("
        "'execution_route', execution_route, "
        "'protocol_version', portable_protocol_version, "
        "'snapshot_manifest_id', snapshot_manifest_id, "
        "'extraction_receipt_id', extraction_receipt_id, "
        "'publication_bundle_id', publication_bundle_id, "
        "'graph_candidate_id', graph_candidate_id, "
        "'source_binding_count', jsonb_array_length(snapshot_vector_json::jsonb), "
        "'family_counts', (SELECT jsonb_object_agg(key, (value->>'count')::bigint) "
        "FROM jsonb_each(family_receipts_json::jsonb))"
        ") FROM latest_portable_publication WHERE graph_id = repo.graph_id), "
        "'raw_observations', ("
        "SELECT COUNT(*) FROM raw_observations "
        "WHERE raw_observations.repository_id = repo.repository_id"
        "), "
        "'raw_observations_total', ("
        "SELECT COUNT(*) FROM raw_observations "
        "WHERE raw_observations.repository_id = repo.repository_id"
        "), "
        "'latest_run_raw_observations', ("
        "SELECT COUNT(*) FROM raw_observations "
        "WHERE raw_observations.repository_id = repo.repository_id "
        "AND raw_observations.run_id = (SELECT id FROM latest_recorded_run "
        "WHERE graph_id = repo.graph_id)"
        "), "
        "'canonical_nodes', ("
        "SELECT COUNT(*) FROM canonical_nodes "
        "WHERE canonical_nodes.repository_id = repo.repository_id"
        "), "
        "'canonical_edges', ("
        "SELECT COUNT(*) FROM canonical_edges "
        "WHERE canonical_edges.repository_id = repo.repository_id"
        ")"
        ") ORDER BY repo.graph_id), '[]'::json)"
        ")::text FROM repo;"
    )


def build_graph_summary_sql(repository_name: str) -> str:
    repository_literal = sql_literal(repository_name)
    return (
        "WITH repo AS ("
        "SELECT repositories.id AS repository_id, repositories.name "
        "FROM repositories "
        f"WHERE repositories.name = {repository_literal} "
        "ORDER BY repositories.id DESC "
        "LIMIT 1"
        "), "
        "latest_recorded_run AS ("
        "SELECT runs.* FROM runs "
        "WHERE runs.repository_id = (SELECT repository_id FROM repo) "
        "ORDER BY runs.id DESC "
        "LIMIT 1"
        "), "
        "file_languages AS ("
        "SELECT language, COUNT(*)::int AS count "
        "FROM files "
        "WHERE repository_id = (SELECT repository_id FROM repo) "
        "GROUP BY language "
        "ORDER BY language"
        "), "
        "observation_kinds AS ("
        "SELECT kind, COUNT(*)::int AS count "
        "FROM raw_observations "
        "WHERE repository_id = (SELECT repository_id FROM repo) "
        "GROUP BY kind "
        "ORDER BY kind"
        "), "
        "latest_recorded_run_observation_kinds AS ("
        "SELECT kind, COUNT(*)::int AS count "
        "FROM raw_observations "
        "WHERE repository_id = (SELECT repository_id FROM repo) "
        "AND run_id = (SELECT id FROM latest_recorded_run) "
        "GROUP BY kind "
        "ORDER BY kind"
        "), "
        "canonical_node_kinds AS ("
        "SELECT kind, COUNT(*)::int AS count "
        "FROM canonical_nodes "
        "WHERE repository_id = (SELECT repository_id FROM repo) "
        "GROUP BY kind "
        "ORDER BY kind"
        "), "
        "canonical_edge_kinds AS ("
        "SELECT edge_kind AS kind, COUNT(*)::int AS count "
        "FROM canonical_edges "
        "WHERE repository_id = (SELECT repository_id FROM repo) "
        "GROUP BY edge_kind "
        "ORDER BY edge_kind"
        ") "
        "SELECT json_build_object("
        "'repository_exists', EXISTS(SELECT 1 FROM repo), "
        "'latest_run_id', (SELECT id FROM latest_recorded_run), "
        "'latest_run_status', (SELECT status FROM latest_recorded_run), "
        "'latest_run_started_at', (SELECT to_char(started_at AT TIME ZONE 'UTC', "
        "'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"') FROM latest_recorded_run), "
        "'latest_run_finished_at', (SELECT to_char(finished_at AT TIME ZONE 'UTC', "
        "'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"') FROM latest_recorded_run), "
        "'files', ("
        "SELECT COUNT(*) FROM files "
        "WHERE repository_id = (SELECT repository_id FROM repo)"
        "), "
        "'raw_observations', ("
        "SELECT COUNT(*) FROM raw_observations "
        "WHERE repository_id = (SELECT repository_id FROM repo)"
        "), "
        "'raw_observations_total', ("
        "SELECT COUNT(*) FROM raw_observations "
        "WHERE repository_id = (SELECT repository_id FROM repo)"
        "), "
        "'latest_run_raw_observations', ("
        "SELECT COUNT(*) FROM raw_observations "
        "WHERE repository_id = (SELECT repository_id FROM repo) "
        "AND run_id = (SELECT id FROM latest_recorded_run)"
        "), "
        "'canonical_nodes', ("
        "SELECT COUNT(*) FROM canonical_nodes "
        "WHERE repository_id = (SELECT repository_id FROM repo)"
        "), "
        "'canonical_edges', ("
        "SELECT COUNT(*) FROM canonical_edges "
        "WHERE repository_id = (SELECT repository_id FROM repo)"
        "), "
        "'language_counts', COALESCE(("
        "SELECT jsonb_object_agg(language, count) FROM file_languages"
        "), '{}'::jsonb), "
        "'observation_kind_counts', COALESCE(("
        "SELECT jsonb_object_agg(kind, count) FROM observation_kinds"
        "), '{}'::jsonb), "
        "'latest_run_observation_kind_counts', COALESCE(("
        "SELECT jsonb_object_agg(kind, count) "
        "FROM latest_recorded_run_observation_kinds"
        "), '{}'::jsonb), "
        "'canonical_node_kind_counts', COALESCE(("
        "SELECT jsonb_object_agg(kind, count) FROM canonical_node_kinds"
        "), '{}'::jsonb), "
        "'canonical_edge_kind_counts', COALESCE(("
        "SELECT jsonb_object_agg(kind, count) FROM canonical_edge_kinds"
        "), '{}'::jsonb)"
        ")::text;"
    )
