from __future__ import annotations

import json
from pathlib import Path, PurePosixPath
import subprocess

import pytest

import ci.file_length_policy as file_length_policy


def load_policy_module():
    return file_length_policy


@pytest.fixture
def policy():
    return file_length_policy


def write_bytes(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)


def initialize_repo(root: Path) -> None:
    (root / "src/main/python").mkdir(parents=True)
    (root / "src/test/unit/python").mkdir(parents=True)
    (root / "tools").mkdir()
    (root / "pyproject.toml").write_text("[project]\n", encoding="utf-8")
    subprocess.run(["git", "init", "-q", str(root)], check=True)


def git_add(root: Path, *paths: str) -> None:
    subprocess.run(["git", "-C", str(root), "add", "--", *paths], check=True)


@pytest.mark.parametrize(
    ("content", "expected"),
    [
        (b"", 0),
        (b"x", 1),
        (b"x\n", 1),
        (b"x\r\n", 1),
        (b"x\r\ny\r\n", 2),
        (b"x\ny", 2),
    ],
)
def test_ci_length0_counts_physical_lines(
    policy,
    tmp_path: Path,
    content: bytes,
    expected: int,
) -> None:
    path = tmp_path / "sample.py"
    path.write_bytes(content)

    assert policy.count_physical_lines(path) == expected


@pytest.mark.parametrize(
    ("line_count", "expected"),
    [
        (0, None),
        (1, None),
        (400, None),
        (401, "warning"),
        (1000, "warning"),
        (1001, "failure"),
    ],
)
def test_ci_length0_classifies_exact_thresholds(policy, line_count, expected) -> None:
    assert policy.classify_line_count(line_count) == expected


def test_ci_length0_discovers_only_tracked_approved_python(policy, tmp_path) -> None:
    root = tmp_path / "repo"
    root.mkdir()
    initialize_repo(root)
    tracked = {
        "src/main/python/app.py": b"x\n",
        "src/test/unit/python/app.unit.test.py": b"x\n",
        "src/test/int/python/app.int.test.py": b"x\n",
        "src/test/support/python/support.py": b"x\n",
        "tools/check.py": b"x\n",
        "tools/with spaces.py": b"x\n",
        "src/main/python/README.md": b"ignored\n",
        "src/test/schema.sql": b"ignored\n",
        "tools/check.sh": b"ignored\n",
    }
    for relative_path, content in tracked.items():
        write_bytes(root / relative_path, content)
    write_bytes(root / "tools/untracked.py", b"x\n")
    write_bytes(root / "tools/ignored.py", b"x\n")
    (root / ".gitignore").write_text("tools/ignored.py\n", encoding="utf-8")
    git_add(root, ".gitignore", "pyproject.toml", *tracked)

    paths = policy.discover_tracked_python_paths(policy.validate_repo_root(root))

    assert paths == [
        PurePosixPath("src/main/python/app.py"),
        PurePosixPath("src/test/int/python/app.int.test.py"),
        PurePosixPath("src/test/support/python/support.py"),
        PurePosixPath("src/test/unit/python/app.unit.test.py"),
        PurePosixPath("tools/check.py"),
        PurePosixPath("tools/with spaces.py"),
    ]


def test_ci_length0_scans_marker_only_python_without_documented_generator(
    policy,
    tmp_path,
) -> None:
    root = tmp_path / "repo"
    root.mkdir()
    initialize_repo(root)
    generated = root / "tools/generated.py"
    write_bytes(
        generated,
        b"# Code generated by tools/generate.py. DO NOT EDIT.\n" + b"x\n" * 1000,
    )
    git_add(root, "pyproject.toml", "tools/generated.py")

    result = policy.scan_repository(policy.validate_repo_root(root))

    assert result.scanned_file_count == 1
    assert result.failure_count == 1


def test_ci_length0_rejects_tracked_symlink(policy, tmp_path) -> None:
    root = tmp_path / "repo"
    root.mkdir()
    initialize_repo(root)
    target = root / "target.py"
    target.write_text("x\n", encoding="utf-8")
    link = root / "tools/link.py"
    link.symlink_to(target)
    git_add(root, "pyproject.toml", "tools/link.py")

    with pytest.raises(policy.FileLengthOperationalError, match="symlink"):
        policy.scan_repository(policy.validate_repo_root(root))


def test_ci_length0_rejects_path_escape(policy, tmp_path) -> None:
    root = tmp_path / "repo"
    root.mkdir()
    initialize_repo(root)

    with pytest.raises(policy.FileLengthOperationalError, match="escapes"):
        policy.resolve_tracked_path(root, PurePosixPath("tools/../../outside.py"))


def test_ci_length0_builds_counts_status_and_path_sorted_findings(policy) -> None:
    result = policy.build_result(
        [
            policy.ScannedFile("tools/z.py", 401),
            policy.ScannedFile("src/main/python/pass.py", 400),
            policy.ScannedFile("src/test/fail.py", 1001),
            policy.ScannedFile("tools/a.py", 500),
        ]
    )

    assert result.status == "failed"
    assert result.scanned_file_count == 4
    assert result.warning_count == 2
    assert result.failure_count == 1
    assert [finding.path for finding in result.findings] == [
        "src/test/fail.py",
        "tools/a.py",
        "tools/z.py",
    ]
    assert all(finding.path != "src/main/python/pass.py" for finding in result.findings)


@pytest.mark.parametrize(
    ("counts", "status"),
    [([1], "passed"), ([401], "passed_with_warnings"), ([1001], "failed")],
)
def test_ci_length0_derives_result_status(policy, counts, status) -> None:
    files = [policy.ScannedFile(f"tools/{index}.py", count) for index, count in enumerate(counts)]

    assert policy.build_result(files).status == status


def test_ci_length0_json_is_deterministic_valid_and_newline_terminated(policy) -> None:
    result = policy.build_result(
        [
            policy.ScannedFile("tools/warning.py", 401),
            policy.ScannedFile("src/main/python/pass.py", 2),
        ]
    )

    first = policy.render_json(result)
    second = policy.render_json(result)
    payload = json.loads(first)

    assert first == second
    assert first.endswith("\n") and not first.endswith("\n\n")
    assert payload == {
        "failure_count": 0,
        "failure_limit": 1000,
        "findings": [
            {"line_count": 401, "path": "tools/warning.py", "severity": "warning"}
        ],
        "profile": "file-length",
        "scanned_file_count": 2,
        "status": "passed_with_warnings",
        "version": 1,
        "warning_count": 1,
        "warning_limit": 400,
    }
    assert str(Path.cwd().resolve()) not in first


def test_ci_length0_text_orders_failures_then_warnings(policy) -> None:
    result = policy.build_result(
        [
            policy.ScannedFile("tools/warning-low.py", 401),
            policy.ScannedFile("tools/failure.py", 1204),
            policy.ScannedFile("tools/warning-high.py", 512),
        ]
    )

    rendered = policy.render_text(result)

    assert rendered.startswith(
        "file-length: failed\n"
        "limits: warning >400, failure >1000\n"
        "scanned: 3 Python files\n"
        "warnings: 2\n"
        "failures: 1\n\n"
    )
    lines = rendered.splitlines()
    assert lines[6:] == [
        "FAILURE  1204  tools/failure.py",
        "WARNING   512  tools/warning-high.py",
        "WARNING   401  tools/warning-low.py",
    ]
    assert rendered.endswith("\n") and not rendered.endswith("\n\n")


def test_ci_length0_text_escapes_control_characters_in_paths(policy) -> None:
    result = policy.build_result(
        [policy.ScannedFile("tools/line\nbreak.py", 401)]
    )

    rendered = policy.render_text(result)

    assert "tools/line\\nbreak.py" in rendered
    assert "tools/line\nbreak.py" not in rendered
