"""Invocation identity for installed checker, runtime and typing inputs."""

from __future__ import annotations

import hashlib
import importlib.metadata
from pathlib import Path
import sys
import sysconfig
from typing import Any


def fingerprint_inputs(roots: set[Path], recorded: set[Path]) -> dict[str, Any]:
    """Bind content and additions, including unrecorded typing inputs."""
    inputs = set(recorded)
    for root in roots:
        inputs.update(path for path in root.rglob("*")
                      if path.is_file() and "__pycache__" not in path.parts
                      and path.suffix not in {".pyc", ".pyo"})
    digest = hashlib.sha256()
    for index, path in enumerate(sorted(inputs)):
        digest.update(str(index).encode() + b"\0" + str(path).encode() + b"\0")
        digest.update(hashlib.sha256(path.read_bytes()).digest())
    return {"input_count": len(inputs), "sha256": digest.hexdigest()}


def bind_environment() -> dict[str, Any]:
    """Hash installed inputs afresh; no saved snapshot authorizes a check.

    RECORD alone cannot detect edits or newly introduced stubs. Walk the active
    installation as well as distribution records, excluding generated bytecode.
    Keep physical paths out of the returned report.
    """
    roots = {Path(sysconfig.get_path(name)).resolve() for name in ("purelib", "platlib")}
    distributions = list(importlib.metadata.distributions())
    versions = sorted((str(d.metadata["Name"]), d.version) for d in distributions)
    inputs: set[Path] = {Path(sys.executable).resolve()}
    # Console binaries may live outside site-packages (notably Ruff).
    for distribution in distributions:
        for entry in distribution.files or ():
            path = Path(str(distribution.locate_file(entry))).absolute()
            if path.is_file() and "__pycache__" not in path.parts:
                inputs.add(path)
    return dict(fingerprint_inputs(roots, inputs), versions=versions)
